# Generated by Django 5.2.9 on 2026-04-24 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('patients', '0003_hmo_patient_patient_type_patient_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_type', models.CharField(choices=[('outpatient', 'Outpatient'), ('retainership', 'Retainership (HMO)')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hmo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to='patients.hmo')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to='billing.service')),
            ],
            options={
                'db_table': 'service_tariffs',
                'ordering': ['service__name', 'patient_type'],
                'unique_together': {('service', 'patient_type', 'hmo')},
            },
        ),
    ]
