import os
import django
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'dannys_wellness.settings')
django.setup()

from billing.models import Service

services = [
    # CLINICAL SERVICES
    ("Echocardiography", "Clinical Services", 12000),
    ("ECG", "Clinical Services", 5000),
    ("Delivery", "Clinical Services", 12000),
    ("Anti Natal", "Clinical Services", 15000),
    ("Abdomino Pelvic Scan", "Clinical Services", 4000),
    ("Pelvic Scan", "Clinical Services", 3000),
    ("Obstetric Scan", "Clinical Services", 3000),
    ("Wound Dressing", "Clinical Services", 1500),
    # PHARMACY - SUSPENSIONS
    ("Susp. Priton", "Pharmacy", 600),
    ("Syrup M. Vite", "Pharmacy", 700),
    ("Syrup PCM", "Pharmacy", 700),
    ("Syrup Emzolyn Child IBT", "Pharmacy", 700),
    ("Syrup Emzolyn Adult IBT", "Pharmacy", 800),
    ("Syrup Vit C", "Pharmacy", 700),
    ("Susp. Fluconazole", "Pharmacy", 1800),
    ("Susp. Metro", "Pharmacy", 700),
    ("Susp Ibuprofen", "Pharmacy", 800),
    ("Susp Lactulose", "Pharmacy", 2300),
    ("Susp. Amoxiclav", "Pharmacy", 3000),
    ("Susp. Albendazole", "Pharmacy", 700),
    ("Susp. Erythromycin", "Pharmacy", 4000),
    ("Susp. Loratadine", "Pharmacy", 1300),
    ("Susp. Artemether", "Pharmacy", 1500),
    ("Susp. Amoxil 125mg", "Pharmacy", 1300),
    ("Susp Asad", "Pharmacy", 500),
    # PHARMACY - TABLETS
    ("Acceclofenac 100mg", "Pharmacy", 700),
    ("Diclofenac 100mg", "Pharmacy", 300),
    ("Tab Erythromycin", "Pharmacy", 800),
    ("Tab Levofloxacin", "Pharmacy", 1700),
    ("Tab Lexotan X10", "Pharmacy", 1000),
    ("Tab Misoprostol", "Pharmacy", 1800),
    ("Tab Metro 200mg X1", "Pharmacy", 20),
    ("Tab Vaginal Insert X1", "Pharmacy", 1200),
    ("Tab PCM 500mg X18", "Pharmacy", 300),
    ("Tab Acycorplus", "Pharmacy", 1300),
    ("Tab Omeprazole 20mg X14", "Pharmacy", 700),
    ("Tab Ibuprofen 400mg", "Pharmacy", 400),
    ("Tab Cefurozine 500mg X10", "Pharmacy", 3000),
    ("Tab Arthemeter 80/480mg X6", "Pharmacy", 1300),
    ("Tab Ciprofloxacine 500mg X10", "Pharmacy", 700),
    ("Tab Aldomet X10", "Pharmacy", 500),
    ("Tab Vasoprin 75mg X10", "Pharmacy", 300),
    ("Tab Daonil 5mg X10", "Pharmacy", 700),
    ("Tab Hyperex 20mg SR X10", "Pharmacy", 1800),
    ("Tab Metformin 500mg X10", "Pharmacy", 600),
    ("Tab Atenolol 100mg X14", "Pharmacy", 1000),
    ("Tab Lisinooril 10mg X14", "Pharmacy", 800),
    ("Tab Amlodipine 10mg X14", "Pharmacy", 800),
    ("Tab Propranol X40mg", "Pharmacy", 1000),
    ("Tab Moderatic X10", "Pharmacy", 400),
    ("Tab Laxis 40mg X10", "Pharmacy", 400),
    ("Tab Losartan Potassium X14", "Pharmacy", 1200),
    ("Tab Ibuprofen 400mg X10", "Pharmacy", 400),
    ("Tab Buscopam 10mg X10", "Pharmacy", 400),
    ("Tab Dexamethasone X10", "Pharmacy", 400),
    ("Tab Tinidazole 500mg X10", "Pharmacy", 400),
    ("Tab Ampiclox 500mg X10", "Pharmacy", 800),
    ("Tab Bendro Fluazide 5mg", "Pharmacy", 700),
    ("Tab Prednisalone", "Pharmacy", 400),
    ("Tab ACT 3", "Pharmacy", 700),
    ("Tab ACT 2", "Pharmacy", 500),
    ("Tab Ibasunate", "Pharmacy", 2500),
    ("Tab Pregabalin 75mg", "Pharmacy", 2500),
    ("Tab Arthrotec", "Pharmacy", 1700),
    ("Zadol Forte", "Pharmacy", 1800),
    ("Tab Augmentin", "Pharmacy", 4000),
    ("Tab Clarithromycin", "Pharmacy", 4500),
    ("Tab Azithromycin 500mg", "Pharmacy", 3000),
    ("Tab Ketoconazole", "Pharmacy", 1000),
    ("Tab Bromazepan 3mg", "Pharmacy", 1000),
    ("Tab Cotrimozole 1 X1", "Pharmacy", 50),
    ("Tab Clopidogrel 75mg", "Pharmacy", 1300),
    ("Tab Cocodamol", "Pharmacy", 4500),
    ("Tab Fansidar X3", "Pharmacy", 400),
    ("Tab Fasolate", "Pharmacy", 10),
    ("Tab Folic Acid", "Pharmacy", 10),
    ("Tab Daonil/Gilbenclamide", "Pharmacy", 700),
    ("Tab Vit B. Complex", "Pharmacy", 10),
    ("Tab Tenofovir Combination", "Pharmacy", 8500),
    ("Tab No-ACH", "Pharmacy", 2500),
    ("Tab Sirdalude 4mg", "Pharmacy", 2500),
    ("Tab Salbutamol 4mg", "Pharmacy", 10),
    ("Tab Ofloxacin", "Pharmacy", 1000),
    ("Tab Amitripphyline", "Pharmacy", 50),
    ("Tab Zinc Sulphate", "Pharmacy", 400),
    ("Tab Vit C X1", "Pharmacy", 10),
    ("Tab Loperamide", "Pharmacy", 400),
    ("Tab Cemetadine 400mg", "Pharmacy", 700),
    ("Tab Dana (Gelosyl)", "Pharmacy", 50),
    ("Tab Loratidine", "Pharmacy", 500),
    ("Tab Nifedifine 20mg", "Pharmacy", 400),
    ("Tab Vit E", "Pharmacy", 1700),
    ("Tab Vit A", "Pharmacy", 1000),
    ("Tab Livolin Forte Card", "Pharmacy", 3200),
    ("Blood Tonic", "Pharmacy", 3500),
    # PHARMACY - CAPSULES
    ("Cap Fluconazole 200mg", "Pharmacy", 1300),
    ("Cap Amoxil Adult", "Pharmacy", 800),
    ("Amoxil Child", "Pharmacy", 600),
    # PHARMACY - CREAMS
    ("Mirapain Cream", "Pharmacy", 1400),
    ("Clotrimazole Cream", "Pharmacy", 1500),
    ("Clotrimazole Insert", "Pharmacy", 1000),
    ("Neurogestic Cream", "Pharmacy", 2300),
    ("Ketoconazole Cream", "Pharmacy", 1000),
    ("Neoskin Cream", "Pharmacy", 1000),
    ("Diclofenac Cream", "Pharmacy", 1000),
    # CONSUMABLES
    ("Scale Vein", "Consumables", 100),
    ("Given Set", "Consumables", 500),
    ("Blood Giving Set", "Consumables", 700),
    ("IV Canula", "Consumables", 500),
    ("Catheter", "Consumables", 1500),
    ("Urine Bag", "Consumables", 800),
    ("Surgical Glove", "Consumables", 400),
    ("Gauze", "Consumables", 500),
    ("Bandage", "Consumables", 700),
    ("Syringe 2mls", "Consumables", 100),
    ("Syringes 5mls", "Consumables", 150),
    ("Syringes 10mls", "Consumables", 200),
    ("ORS X1", "Consumables", 250),
    ("N. G Tube", "Consumables", 800),
    # PHARMACY - INJECTIONS
    ("Inj. Penta", "Pharmacy", 1800),
    ("Inj. Hyosin", "Pharmacy", 400),
    ("Inj. PCM 300mg", "Pharmacy", 300),
    ("Inj. Diazepan", "Pharmacy", 700),
    ("Inj. Diclo 75mg", "Pharmacy", 300),
    ("Inj. Hydrocort", "Pharmacy", 800),
    ("Inj. Omeprazole 70mg", "Pharmacy", 700),
    ("IV Metro", "Pharmacy", 1200),
    ("IV Cipro", "Pharmacy", 1200),
    ("IV Omeprazole", "Pharmacy", 1200),
    ("Inj. Insulin", "Pharmacy", 7500),
    ("Inj. Genta", "Pharmacy", 400),
    ("Inj. Exacef", "Pharmacy", 4500),
    ("Inj. Dexamethasone", "Pharmacy", 400),
    ("Inj. Plasil", "Pharmacy", 400),
    ("Inj. Prometh", "Pharmacy", 300),
    ("Inj. Frusamide", "Pharmacy", 500),
    ("Inj. Quinine", "Pharmacy", 700),
    ("Inj. Ranitidine", "Pharmacy", 750),
    ("IV Artesunate 120mg", "Pharmacy", 3500),
    ("Inj. Artemether 80mg X6", "Pharmacy", 2000),
    ("Inj. Imal Non Branded", "Pharmacy", 3500),
    ("Inj. Imal Branded", "Pharmacy", 7500),
    ("Inj. Aminophyllin", "Pharmacy", 700),
    ("Inj. Tandak", "Pharmacy", 4500),
    ("IV Ceftriaxone LG", "Pharmacy", 1300),
    ("IV Artesunate 60mg/Rekmal", "Pharmacy", 1700),
    ("IV Rekmal 30mg", "Pharmacy", 2200),
    ("Inj T.T", "Pharmacy", 700),
    ("Inj. B. Complex", "Pharmacy", 500),
    ("Inj. Amoxiclav 1.2mg", "Pharmacy", 3200),
    ("Inj. Amoxiclav 0.6", "Pharmacy", 3500),
    # PHARMACY - IV FLUIDS
    ("IVF D/S", "Pharmacy", 1500),
    ("IVF N/S", "Pharmacy", 1300),
    ("IVF D/W", "Pharmacy", 1300),
    ("IVF 4.3", "Pharmacy", 1300),
    ("IVF Ringers Lactate", "Pharmacy", 1500),
    ("IVF Manitol", "Pharmacy", 2500),
    ("IV FSD", "Pharmacy", 1500),
    # PHARMACY - OTHERS
    ("Piroxicam", "Pharmacy", 700),
    ("Doxycycline", "Pharmacy", 500),
    ("Fluconazole", "Pharmacy", 1400),
    ("Calamine Lotion", "Pharmacy", 600),
    ("Neurovite Forte", "Pharmacy", 1800),
    ("Antacid Susp", "Pharmacy", 1300),
    ("Artemethine Lumephantone 80/486", "Pharmacy", 1250),
    # LABORATORY TESTS
    ("MP (Malaria Parasite)", "Laboratory", 1000),
    ("Widal", "Laboratory", 2000),
    ("PCV", "Laboratory", 1000),
    ("Urinalysis", "Laboratory", 1000),
    ("PT (Pregnancy Test)", "Laboratory", 1000),
    ("HCV", "Laboratory", 1000),
    ("HBV", "Laboratory", 2000),
    ("ARC/RVS", "Laboratory", 3000),
    ("FBC (Full Blood Count)", "Laboratory", 1000),
    ("ESR", "Laboratory", 1500),
    ("Blood Grouping", "Laboratory", 1000),
    ("RBS (Random Blood Sugar)", "Laboratory", 1000),
    ("FBS (Fasting Blood Sugar)", "Laboratory", 1000),
    ("2HPP", "Laboratory", 2500),
    ("Urine M/C/S", "Laboratory", 2500),
    ("Stool M/C/S", "Laboratory", 2000),
    ("Stool Microscopy", "Laboratory", 1500),
    ("Occult Blood", "Laboratory", 2500),
    ("HVS MCS", "Laboratory", 7000),
    ("HbA1C", "Laboratory", 7000),
    ("AFP ()", "Laboratory", 7500),
    ("Lipid Profile", "Laboratory", 2500),
    ("Genotype", "Laboratory", 4000),
    ("PSA Qualitative", "Laboratory", 12000),
    ("PSA Quantitative", "Laboratory", 7000),
    ("Rheumatoid Factor", "Laboratory", 3000),
    ("H. Pylori", "Laboratory", 2500),
    ("Urea", "Laboratory", 2500),
    ("Creatinine", "Laboratory", 2500),
    ("Cholesterol", "Laboratory", 2500),
    ("Uric Acid", "Laboratory", 3500),
    ("Calcium", "Laboratory", 4000),
    ("ASL", "Laboratory", 2000),
    ("ALT", "Laboratory", 2000),
    ("LFT (Liver Function Test)", "Laboratory", 8000),
    ("E/U/CR", "Laboratory", 9000),
    ("Electrolyte", "Laboratory", 3500),
    ("Albumin", "Laboratory", 2000),
    ("HBV Quantification", "Laboratory", 12000),
    ("HBV (DNA)", "Laboratory", 35000),
    ("HCV RNA", "Laboratory", 35000),
    ("BCV Genotype", "Laboratory", 35000),
    ("Viral Screening (Donor Screening)", "Laboratory", 4500),
    ("T3 T4 and TSA", "Laboratory", 30000),
    ("HB Serology/Profile", "Laboratory", 5500),
    ("Total Bilirubin", "Laboratory", 2500),
    ("Plural Fluid AFB", "Laboratory", 3500),
    ("RFT/E/U/Cr", "Laboratory", 9000),
    ("VDRL", "Laboratory", 1000),
    ("ARC Viral Load (RNA)", "Laboratory", 25000),
    ("Asetic Fluid Analysis (AFAB)", "Laboratory", 3500),
    ("AFAC", "Laboratory", 4500),
    ("AFA Haem", "Laboratory", 4000),
    ("A Feto Protein Quantitative", "Laboratory", 17000),
    ("Magnesium", "Laboratory", 5000),
    ("Organic Phosphate", "Laboratory", 5000),
    ("Viral Maker", "Laboratory", 6000),
    ("Rheumatoid Factor +VE", "Laboratory", 17000),
    ("Blood Culture", "Laboratory", 3500),
    ("CD4 Count", "Laboratory", 3000),
]

created = 0
updated = 0
for name, category, price in services:
    obj, was_created = Service.objects.update_or_create(
        name=name,
        defaults={"category": category, "price": price, "is_active": True}
    )
    if was_created:
        created += 1
        print(f"  Created: {name} - ₦{price:,}")
    else:
        updated += 1
        print(f"  Updated: {name} - ₦{price:,}")

print(f"\nDone! {created} created, {updated} updated. Total: {created + updated} services.")
