import os
import django
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'dannys_wellness.settings')
django.setup()

from billing.models import Service, ServiceTariff
from patients.models import HMO

try:
    hmo = HMO.objects.get(name__icontains='NHIS')
    print(f"HMO: {hmo.name} ({hmo.code})")
except HMO.DoesNotExist:
    print("ERROR: NHIS HMO not found."); exit()

# NHIS Professional Fee-for-Service (FFS) Price List October 2021
# Format: (Name, Category, Price)
services = [
    # ── GENERAL CONSULTATIONS ─────────────────────────────────────────
    ("Specialist Initial Consultation NHIS", "Clinical Services", 2000),
    ("Specialist Review Per Visit NHIS", "Clinical Services", 1200),
    ("Nursing Care Per Day NHIS", "Clinical Services", 1000),
    ("Special Nursing Care ICU SCBU NHIS", "Clinical Services", 1200),
    ("Hospital Bed Occupancy NHIS", "Clinical Services", 1000),
    ("ICU Nursing Care Per Day NHIS", "Clinical Services", 2000),

    # ── ENT / MAXILLOFACIAL - MINOR ───────────────────────────────────
    ("Antral Washout ENT NHIS", "Clinical Services", 20000),
    ("Audiometry NHIS", "Clinical Services", 10000),
    ("Electrocautery of Nose NHIS", "Clinical Services", 20000),
    ("Foreign Body Removal from Ear NHIS", "Clinical Services", 5000),
    ("Foreign Body Removal from Nose Ordinary NHIS", "Clinical Services", 5000),
    ("Foreign Body Removal from Nose Under GA NHIS", "Clinical Services", 15000),
    ("Foreign Body Removal from Throat NHIS", "Clinical Services", 15000),
    ("I&D Quinsy Retropharyngeal Abscess NHIS", "Clinical Services", 15000),
    ("Indirect Laryngoscopy NHIS", "Clinical Services", 15000),
    ("Myringoplasty NHIS", "Clinical Services", 30000),
    ("Myringotomy Bilateral Unilateral NHIS", "Clinical Services", 20000),
    ("Preauricular Sinus Repair NHIS", "Clinical Services", 18000),
    ("Release of Tongue Tie NHIS", "Clinical Services", 15000),
    ("Sinus Antroscopy NHIS", "Clinical Services", 15000),
    ("Tympanometry NHIS", "Clinical Services", 10000),
    ("Ear Syringing Per Ear NHIS", "Clinical Services", 2500),
    ("Simple Dental Extraction NHIS", "Clinical Services", 5000),
    ("Surgical Dental Extraction NHIS", "Clinical Services", 10000),

    # ── ENT - INTERMEDIATE ────────────────────────────────────────────
    ("Adenoidectomy ENT NHIS", "Clinical Services", 30000),
    ("Antrostomy Nasal Sinus Surgery NHIS", "Clinical Services", 30000),
    ("Cleft Lip Repairs NHIS", "Clinical Services", 30000),
    ("Cortical Mastoidectomy NHIS", "Clinical Services", 30000),
    ("Direct Laryngoscopy Under GA NHIS", "Clinical Services", 30000),
    ("Nasal Polypectomy NHIS", "Clinical Services", 30000),
    ("Oesophagoscopy ENT NHIS", "Clinical Services", 25000),
    ("Septoplasty NHIS", "Clinical Services", 25000),
    ("Submandibular Gland Excision NHIS", "Clinical Services", 30000),
    ("Superficial Parotidectomy NHIS", "Clinical Services", 30000),
    ("Thyroglossal Cyst Fistula Excision ENT NHIS", "Clinical Services", 30000),
    ("Tonsillectomy Adenotonsilectomy NHIS", "Clinical Services", 30000),
    ("Tracheostomy NHIS", "Clinical Services", 30000),
    ("Turbinectomy NHIS", "Clinical Services", 30000),

    # ── ENT - MAJOR ───────────────────────────────────────────────────
    ("Cleft Palate Repairs NHIS", "Clinical Services", 60000),
    ("Fracture Reduction of the Nose NHIS", "Clinical Services", 60000),
    ("Laryngectomy All Types NHIS", "Clinical Services", 150000),
    ("Mastoid Surgery Mastoidectomy NHIS", "Clinical Services", 60000),
    ("Maxillectomy NHIS", "Clinical Services", 60000),
    ("Neck Exploration Penetrating Neck Injury NHIS", "Clinical Services", 150000),
    ("Rhinoplasty NHIS", "Clinical Services", 60000),
    ("Stapedial Surgery Otosclerosis Stapedectomy NHIS", "Clinical Services", 65000),
    ("Total Parotidectomy NHIS", "Clinical Services", 60000),
    ("Tympanoplasty NHIS", "Clinical Services", 62500),
    ("Fixation of Fracture of the Jaw NHIS", "Clinical Services", 45000),

    # ── OBSTETRICS & GYNAECOLOGY - GENERAL ───────────────────────────
    ("Antenatal Care NHIS", "Clinical Services", 10000),
    ("Normal Delivery NHIS", "Clinical Services", 10000),
    ("Delivery of Multiple Pregnancy NHIS", "Clinical Services", 15000),

    # ── O&G - MINOR ───────────────────────────────────────────────────
    ("Cervical Polypectomy NHIS", "Clinical Services", 20000),
    ("Cervical Cone Biopsy NHIS", "Clinical Services", 20000),
    ("Colposcopy NHIS", "Clinical Services", 20000),
    ("D&C Evacuation Retained Products NHIS", "Clinical Services", 20000),
    ("Hysteroscopy NHIS", "Clinical Services", 25000),
    ("Laparoscopy Dye Test NHIS", "Clinical Services", 25000),
    ("Marsupialisation Bartholins Cyst NHIS", "Clinical Services", 25000),
    ("Pap Smear Procedure NHIS", "Clinical Services", 5000),
    ("Repair of Episiotomy NHIS", "Clinical Services", 10000),
    ("Uterine Evacuation NHIS", "Clinical Services", 20000),
    ("Vaginal Cyst Enucleation Under LA NHIS", "Clinical Services", 20000),
    ("Vaginal Cyst Enucleation Under GA NHIS", "Clinical Services", 50000),

    # ── O&G - INTERMEDIATE ────────────────────────────────────────────
    ("Cervical Circlage Shirodkar Suture NHIS", "Clinical Services", 40000),
    ("Colporrhaphy Vaginal Wall Repair NHIS", "Clinical Services", 35000),
    ("Diagnostic Laparoscopy NHIS", "Clinical Services", 35000),
    ("Laparoscopy Therapeutic NHIS", "Clinical Services", 50000),
    ("Instrumental Delivery Forceps Vacuum NHIS", "Clinical Services", 30000),
    ("Mini Laparotomy NHIS", "Clinical Services", 40000),
    ("Repair of Third Degree Tear NHIS", "Clinical Services", 20000),

    # ── O&G - MAJOR ───────────────────────────────────────────────────
    ("Bilateral Tubal Ligation NHIS", "Clinical Services", 55000),
    ("Caesarean Section NHIS", "Clinical Services", 70000),
    ("Caesarean Section with BTL NHIS", "Clinical Services", 80000),
    ("Caesarean Section with Hysterectomy NHIS", "Clinical Services", 90000),
    ("Hysterectomy Bilateral Salpingo-Oophorectomy NHIS", "Clinical Services", 100000),
    ("Hysterectomy Manchester Repair NHIS", "Clinical Services", 68000),
    ("Laparotomy Diagnostic Therapeutic NHIS", "Clinical Services", 68000),
    ("Myomectomy Abdominal NHIS", "Clinical Services", 75000),
    ("Ovarectomy Oophrectomy NHIS", "Clinical Services", 68000),
    ("Rectovaginal Fistula Repair NHIS", "Clinical Services", 75000),
    ("Repair of Ruptured Uterus NHIS", "Clinical Services", 75000),
    ("Salpingectomy Ectopic Pregnancy NHIS", "Clinical Services", 65000),
    ("Vesicovaginal Fistula Repair O&G NHIS", "Clinical Services", 55000),
    ("Vulvectomy O&G NHIS", "Clinical Services", 68000),

    # ── INTERNAL MEDICINE ─────────────────────────────────────────────
    ("Aspiration Internal Medicine NHIS", "Clinical Services", 2500),
    ("Aspiration USS Guided NHIS", "Clinical Services", 5000),
    ("Diagnostic Paracentesis NHIS", "Clinical Services", 2500),
    ("Haemodialysis Per Session NHIS", "Clinical Services", 26000),
    ("Therapeutic Paracentesis NHIS", "Clinical Services", 10000),
    ("Critical Care ICU Per Day NHIS", "Clinical Services", 7500),
    ("Bed Fee Per Day NHIS", "Clinical Services", 1000),
    ("Mechanical Ventilation Per Day NHIS", "Clinical Services", 5000),
    ("Oxygen Therapy Per Day NHIS", "Clinical Services", 10000),
    ("Oxygen Therapy Per Hour NHIS", "Clinical Services", 500),
    ("Central Venous Cannulation Per Session NHIS", "Clinical Services", 10000),
    ("Endotracheal Intubation Per Session NHIS", "Clinical Services", 5000),
    ("Echocardiography Internal Medicine NHIS", "Clinical Services", 10000),
    ("Electrocardiography ECG NHIS", "Clinical Services", 5000),
    ("Electro-Encephalography EEG NHIS", "Clinical Services", 15000),
    ("24 Hour ECG Holter ECG NHIS", "Clinical Services", 15000),
    ("Exercise ECG NHIS", "Clinical Services", 7500),
    ("Ambulatory BP Monitoring NHIS", "Clinical Services", 5000),
    ("Gastric Lavage NHIS", "Clinical Services", 2500),
    ("Lumbar Puncture NHIS", "Clinical Services", 2500),
    ("Lung Function Test NHIS", "Clinical Services", 5000),
    ("Nebulisation Per Session NHIS", "Clinical Services", 2000),
    ("Tissue Biopsy Liver Kidney NHIS", "Clinical Services", 10000),
    ("Skin Biopsy NHIS", "Clinical Services", 5000),
    ("Bone Marrow Biopsy NHIS", "Clinical Services", 10000),

    # ── ORTHOPAEDICS - POP CASTS ─────────────────────────────────────
    ("Above Knee POP Cast NHIS", "Clinical Services", 10000),
    ("Below Knee POP Cast NHIS", "Clinical Services", 10000),
    ("Above Elbow POP Cast NHIS", "Clinical Services", 10000),
    ("Below Elbow POP Cast NHIS", "Clinical Services", 10000),
    ("Hip Spica POP Cast NHIS", "Clinical Services", 15000),
    ("Thoracolumbar POP Cast NHIS", "Clinical Services", 15000),
    ("Full Arm Casts NHIS", "Clinical Services", 10000),
    ("Full Leg Casts NHIS", "Clinical Services", 10000),
    ("Scotch Cast NHIS", "Clinical Services", 15000),
    ("Removal of POP NHIS", "Clinical Services", 2500),

    # ── ORTHOPAEDICS - MINOR ─────────────────────────────────────────
    ("Amputation Fingers NHIS", "Clinical Services", 18000),
    ("Amputation Toes NHIS", "Clinical Services", 18000),
    ("Excision Biopsy Ortho NHIS", "Clinical Services", 15000),
    ("Knee Effusion Tap NHIS", "Clinical Services", 15000),
    ("Synovectomy NHIS", "Clinical Services", 18000),

    # ── ORTHOPAEDICS - INTERMEDIATE ──────────────────────────────────
    ("Closed Reduction of Fracture NHIS", "Clinical Services", 30000),
    ("Drainage of Septic Arthritis NHIS", "Clinical Services", 30000),
    ("Sequestrectomy Ortho NHIS", "Clinical Services", 30000),
    ("Skin Traction Application NHIS", "Clinical Services", 3000),
    ("Subperiosteal Drainage Acute Osteomyelitis NHIS", "Clinical Services", 25000),

    # ── ORTHOPAEDICS - MAJOR ─────────────────────────────────────────
    ("Amputation and Disarticulation of Joints NHIS", "Clinical Services", 100000),
    ("Arthrodesis NHIS", "Clinical Services", 100000),
    ("Arthroplasty NHIS", "Clinical Services", 100000),
    ("Bone Grafting NHIS", "Clinical Services", 25000),
    ("Open Reduction Internal Fixation Fracture Leg NHIS", "Clinical Services", 100000),
    ("Open Reduction Internal Fixation Fracture Thigh NHIS", "Clinical Services", 100000),
    ("Open Reduction Internal Fixation Fracture Forearm NHIS", "Clinical Services", 100000),
    ("Open Reduction Internal Fixation Fracture Spinal Column NHIS", "Clinical Services", 150000),
    ("Tendon Grafting NHIS", "Clinical Services", 100000),
    ("Tendon Transplant NHIS", "Clinical Services", 100000),
    ("Decompression Carpal Tunnel Syndrome NHIS", "Clinical Services", 100000),

    # ── GENERAL SURGERY - MINOR ──────────────────────────────────────
    ("Adventious Bursae Excision NHIS", "Clinical Services", 20000),
    ("Biopsy of Prostate NHIS", "Clinical Services", 20000),
    ("Cervical Lymph Nodes Excision NHIS", "Clinical Services", 20000),
    ("Circumcision Grown Up NHIS", "Clinical Services", 20000),
    ("Debridement Toilet of Wounds NHIS", "Clinical Services", 20000),
    ("Excision of Breast Lump NHIS", "Clinical Services", 20000),
    ("Fibroadenoma Unilateral NHIS", "Clinical Services", 20000),
    ("Ganglion Excision NHIS", "Clinical Services", 20000),
    ("Gastroduodenoscopy Endoscopies NHIS", "Clinical Services", 20000),
    ("Herniotomy NHIS", "Clinical Services", 20000),
    ("Incision And Drainage of Abscess NHIS", "Clinical Services", 20000),
    ("In-growing Toenail Excision NHIS", "Clinical Services", 20000),
    ("Intercostals Drainage Insertion NHIS", "Clinical Services", 20000),
    ("Liver Kidney Bone Marrow Biopsy NHIS", "Clinical Services", 20000),
    ("Lumpectomy Excision NHIS", "Clinical Services", 20000),
    ("Paracentesis AC Wash Out NHIS", "Clinical Services", 20000),
    ("Pericardiocentesis NHIS", "Clinical Services", 20000),
    ("Proctoscopy NHIS", "Clinical Services", 20000),
    ("Punch Biopsy NHIS", "Clinical Services", 10000),
    ("Sebaceous Cyst Excision NHIS", "Clinical Services", 20000),
    ("Sigmoidoscopy NHIS", "Clinical Services", 20000),
    ("Surgical Drainage Anal Abscess NHIS", "Clinical Services", 20000),
    ("Suture of Major Wounds NHIS", "Clinical Services", 20000),
    ("Testicular Biopsy NHIS", "Clinical Services", 20000),
    ("Varicocoelectomy NHIS", "Clinical Services", 20000),

    # ── GENERAL SURGERY - INTERMEDIATE ───────────────────────────────
    ("Anal Fistulectomy Repair NHIS", "Clinical Services", 40000),
    ("Appendicetomy NHIS", "Clinical Services", 35000),
    ("Bronchoscopy Gen Surgery NHIS", "Clinical Services", 35000),
    ("Cystourethroscopy NHIS", "Clinical Services", 35000),
    ("Fissurectomy NHIS", "Clinical Services", 35000),
    ("Fistula In Ano Repair NHIS", "Clinical Services", 35000),
    ("Haemorhoidectomy NHIS", "Clinical Services", 35000),
    ("Herniorhaphies All Types NHIS", "Clinical Services", 35000),
    ("Hydrocoelectomy NHIS", "Clinical Services", 35000),
    ("Orchidectomy NHIS", "Clinical Services", 35000),
    ("Orchidopexy NHIS", "Clinical Services", 35000),
    ("Skin Grafting NHIS", "Clinical Services", 35000),
    ("Suprapubic Cystostomy NHIS", "Clinical Services", 35000),
    ("Vasectomy NHIS", "Clinical Services", 35000),

    # ── GENERAL SURGERY - MAJOR ───────────────────────────────────────
    ("Appendicular Abscess Drainage NHIS", "Clinical Services", 75000),
    ("Axillary Dissection of Breast NHIS", "Clinical Services", 75000),
    ("Cholecystectomy NHIS", "Clinical Services", 75000),
    ("Cholecystectomy Exploration NHIS", "Clinical Services", 75000),
    ("Colectomy Partial Total NHIS", "Clinical Services", 75000),
    ("Colostomy Construction Closure NHIS", "Clinical Services", 75000),
    ("Craniotomy NHIS", "Clinical Services", 75000),
    ("Cystectomy Partial Total NHIS", "Clinical Services", 75000),
    ("Exploratory Laparatomy Lysis Adhesions NHIS", "Clinical Services", 75000),
    ("Gastrectomy Partial Total NHIS", "Clinical Services", 75000),
    ("Gastroenterostomy NHIS", "Clinical Services", 75000),
    ("Hemicolectomy NHIS", "Clinical Services", 75000),
    ("Hepatic Resection Lobectomy NHIS", "Clinical Services", 75000),
    ("Hypospadiacs Repair NHIS", "Clinical Services", 75000),
    ("Ileostomy NHIS", "Clinical Services", 75000),
    ("Intestinal Obstruction Surgery NHIS", "Clinical Services", 75000),
    ("Laparascopic Cholecystectomy NHIS", "Clinical Services", 75000),
    ("Laparotomy NHIS", "Clinical Services", 75000),
    ("Mastectomy NHIS", "Clinical Services", 75000),
    ("Nephrectomy NHIS", "Clinical Services", 75000),
    ("Nephrolithotomy NHIS", "Clinical Services", 75000),
    ("Oesophagectomy NHIS", "Clinical Services", 75000),
    ("Pancreatectomy Partial NHIS", "Clinical Services", 75000),
    ("Pericardiectomy NHIS", "Clinical Services", 75000),
    ("Pneumonectomy NHIS", "Clinical Services", 75000),
    ("Prostatectomy All Types TURP NHIS", "Clinical Services", 75000),
    ("Pyelolithotomy NHIS", "Clinical Services", 75000),
    ("Pyloroplasty NHIS", "Clinical Services", 75000),
    ("Radical Cystectomy NHIS", "Clinical Services", 85000),
    ("Radical Mastectomy NHIS", "Clinical Services", 85000),
    ("Radical Neck Dissection NHIS", "Clinical Services", 85000),
    ("Radical Prostatectomy NHIS", "Clinical Services", 85000),
    ("Reconstruction of The Ureter NHIS", "Clinical Services", 90000),
    ("Repair of Bowel Perforations NHIS", "Clinical Services", 75000),
    ("Repair of Common Bile Duct NHIS", "Clinical Services", 75000),
    ("Resection Anastomosis Large Intestine NHIS", "Clinical Services", 75000),
    ("Resection Anastomosis Small Intestine NHIS", "Clinical Services", 75000),
    ("Splenectomy NHIS", "Clinical Services", 75000),
    ("Subtotal Thyroidectomy NHIS", "Clinical Services", 75000),
    ("Thoracotomy NHIS", "Clinical Services", 75000),
    ("Thyroidectomy NHIS", "Clinical Services", 75000),
    ("Ureterolithotomy NHIS", "Clinical Services", 75000),
    ("Urethroplasty NHIS", "Clinical Services", 75000),
    ("Vesicovaginal Fistula Repair Gen Surgery NHIS", "Clinical Services", 55000),
    ("Vulvectomy Gen Surgery NHIS", "Clinical Services", 75000),
    ("Wound Debridement Under GA NHIS", "Clinical Services", 50000),

    # ── ENDOSCOPIC PROCEDURES (partial coverage) ──────────────────────
    ("Appendectomy Endoscopic NHIS", "Clinical Services", 55000),
    ("Cholecystectomy Endoscopic NHIS", "Clinical Services", 60000),
    ("Hemicolectomy Endoscopic NHIS", "Clinical Services", 60000),
    ("Hysterectomy Bilateral SalpingoOphrectomy Endoscopic NHIS", "Clinical Services", 75000),
    ("Incisional Hernia Repair Endoscopic NHIS", "Clinical Services", 75000),
    ("Inguinal Hernia Bilateral Endoscopic NHIS", "Clinical Services", 75000),
    ("Inguinal Hernia Unilateral Endoscopic NHIS", "Clinical Services", 75000),
    ("Intestinal Resection Endoscopic NHIS", "Clinical Services", 75000),
    ("Myomectomy Endoscopic NHIS", "Clinical Services", 75000),
    ("Oophrectomy Endoscopic NHIS", "Clinical Services", 45000),
    ("Ovarian Cystectomy Endoscopic NHIS", "Clinical Services", 45000),
    ("Salpingo Ophrectomy Endoscopic NHIS", "Clinical Services", 45000),
    ("Varicocele Bilateral Endoscopic NHIS", "Clinical Services", 60000),
    ("Bronchoscopy Endoscopic NHIS", "Clinical Services", 35000),
    ("Upper GI Endoscopy NHIS", "Clinical Services", 35000),
    ("Lower GI Endoscopy NHIS", "Clinical Services", 50000),

    # ── OPTOMETRY ─────────────────────────────────────────────────────
    ("Manual Refraction NHIS", "Clinical Services", 1500),
    ("Auto Refraction NHIS", "Clinical Services", 2500),
    ("Tonometry Pulsair Goldmann Applanation NHIS", "Clinical Services", 4000),
    ("Indirect Ophthalmoscopy NHIS", "Clinical Services", 5000),
    ("Direct Ophthalmoscopy NHIS", "Clinical Services", 2000),
    ("Visual Field Assessment NHIS", "Clinical Services", 5000),
    ("Slit Lamp Examination NHIS", "Clinical Services", 3000),
    ("Foreign Body Removal Eye NHIS", "Clinical Services", 5000),
    ("Corneal Pachymetry NHIS", "Clinical Services", 3000),
    ("Keratometry NHIS", "Clinical Services", 4000),
    ("Gonioscopy NHIS", "Clinical Services", 3000),
    ("Low Priced Spectacles Frame Lens NHIS", "Clinical Services", 10000),
    ("Fundus Photography NHIS", "Clinical Services", 15000),
    ("Low Vision Assessment NHIS", "Clinical Services", 10000),
    ("Color Vision Test NHIS", "Clinical Services", 1500),
    ("Dry Eye Assessment Schirmers Test NHIS", "Clinical Services", 2000),
    ("Visual Acuity Testing NHIS", "Clinical Services", 500),
    ("Eye Dressing NHIS", "Clinical Services", 500),

    # ── OPHTHALMOLOGY ─────────────────────────────────────────────────
    ("Cataract Removal Bilateral NHIS", "Clinical Services", 30000),
    ("Cataract Removal Unilateral NHIS", "Clinical Services", 50000),
    ("Chalazion Excision NHIS", "Clinical Services", 20000),
    ("Combined Cataract Extraction Trabeculectomy NHIS", "Clinical Services", 75000),
    ("Corneal Grafting NHIS", "Clinical Services", 75000),
    ("Dacrocystorhinostomy NHIS", "Clinical Services", 75000),
    ("Ectropion Correction NHIS", "Clinical Services", 35000),
    ("Entropion And Ectropion Repairs NHIS", "Clinical Services", 35000),
    ("Evisceration Enucleation Extenteration NHIS", "Clinical Services", 70000),
    ("Extracapsular Cataract Extraction NHIS", "Clinical Services", 45000),
    ("Keratoplasty NHIS", "Clinical Services", 80000),
    ("Lacrimal Probing and Syringing NHIS", "Clinical Services", 15000),
    ("Lensectomy NHIS", "Clinical Services", 50000),
    ("Limbal Dermoid Removal NHIS", "Clinical Services", 20000),
    ("Penetrating Keratoplasty NHIS", "Clinical Services", 75000),
    ("Pterigium Conjunctival Autograft NHIS", "Clinical Services", 35000),
    ("Pterygium Excision NHIS", "Clinical Services", 20000),
    ("Ptosis Repair NHIS", "Clinical Services", 75000),
    ("Removal of Foreign Bodies Conjuctiva Cornea NHIS", "Clinical Services", 5000),
    ("Retinal Detachment Surgery NHIS", "Clinical Services", 150000),
    ("Scleral Buckling Procedures NHIS", "Clinical Services", 80000),
    ("Socket Reconstruction NHIS", "Clinical Services", 75000),
    ("Squint Surgery NHIS", "Clinical Services", 50000),
    ("Trabeculectomy With Antimetabolites NHIS", "Clinical Services", 75000),
    ("Traumatic Lid Laceration Repair NHIS", "Clinical Services", 20000),
    ("Vitrectomy NHIS", "Clinical Services", 35000),
    ("Fundus Imaging NHIS", "Clinical Services", 15000),
    ("Phaco Cataract Surgery NHIS", "Clinical Services", 100000),
    ("Small Incision Cataract Surgery SICS NHIS", "Clinical Services", 60000),
    ("Extracapsular Cataract Extraction ECCE NHIS", "Clinical Services", 50000),
    ("Trabeculectomy NHIS", "Clinical Services", 50000),
    ("Biometry NHIS", "Clinical Services", 5000),
    ("Flourescein Angiography NHIS", "Clinical Services", 30000),
    ("Chalazion Incision Curretage NHIS", "Clinical Services", 25000),

    # ── PSYCHIATRIC SERVICES ──────────────────────────────────────────
    ("Electroconvulsive Therapy Per Session NHIS", "Clinical Services", 5000),
    ("Comprehensive Psychiatric Assessment NHIS", "Clinical Services", 5000),
    ("Psychotherapies Per Session NHIS", "Clinical Services", 4000),
    ("Behaviour Modifications NHIS", "Clinical Services", 4000),
    ("Electroencephalography Psychiatric NHIS", "Clinical Services", 15000),

    # ── PAEDIATRICS ───────────────────────────────────────────────────
    ("Paediatric Bed Fee Per Day NHIS", "Clinical Services", 2000),
    ("Paediatric Nursing Care Per Day NHIS", "Clinical Services", 1250),
    ("Paediatric Mechanical Ventilation Per Day NHIS", "Clinical Services", 2500),
    ("Paediatric Oxygen Therapy Per Day NHIS", "Clinical Services", 7500),
    ("Paediatric Endotracheal Intubation NHIS", "Clinical Services", 2500),
    ("Paediatric Lumbar Puncture NHIS", "Clinical Services", 1500),
    ("Phototherapy Per Day NHIS", "Clinical Services", 1500),
    ("Incubator Care Per Day NHIS", "Clinical Services", 2000),
    ("Exchange Blood Transfusion NHIS", "Clinical Services", 15000),
    ("Subdural Tap NHIS", "Clinical Services", 4000),
    ("Hernia Inguinal Bilateral Paeds NHIS", "Clinical Services", 25000),
    ("Hernia Inguinal Unilateral Paeds NHIS", "Clinical Services", 25000),
    ("Orchidopexy Unilateral Paeds NHIS", "Clinical Services", 30000),
    ("Orchidopexy Bilateral Paeds NHIS", "Clinical Services", 60000),
    ("Circumcision Paeds NHIS", "Clinical Services", 5000),
    ("Appendectomy Paeds NHIS", "Clinical Services", 35000),
    ("Hypospadias Repair Paeds NHIS", "Clinical Services", 50000),
    ("Rectal Biopsy Paeds NHIS", "Clinical Services", 15000),
    ("Pull Through Hirshprungs Disease NHIS", "Clinical Services", 100000),
    ("Uretheral Catheterisation Paeds NHIS", "Clinical Services", 1500),

    # ── DENTAL SURGERY ────────────────────────────────────────────────
    ("Dental X-Ray Periapical NHIS", "Clinical Services", 1500),
    ("Dental X-Ray Bitewings NHIS", "Clinical Services", 2000),
    ("Dental X-Ray Panoramic View NHIS", "Clinical Services", 2500),
    ("Scaling Polishing Heavy Therapeutic NHIS", "Clinical Services", 3500),
    ("Scaling Polishing Light Therapeutic NHIS", "Clinical Services", 3000),
    ("Dental Curretage NHIS", "Clinical Services", 1000),
    ("Amalgam Restoration NHIS", "Clinical Services", 3500),
    ("Amalgam Restoration Class II NHIS", "Clinical Services", 4000),
    ("Composite Restoration NHIS", "Clinical Services", 4000),
    ("Periodontal Gum Treatment NHIS", "Clinical Services", 3000),
    ("Fissure Selant Dental NHIS", "Clinical Services", 2000),
    ("Root Canal Therapy Anterior NHIS", "Clinical Services", 10000),
    ("Root Canal Therapy Posterior NHIS", "Clinical Services", 15000),
    ("Dentures NHIS", "Clinical Services", 5000),

    # ── PHYSIOTHERAPY ─────────────────────────────────────────────────
    ("Physiotherapy Cerebrovascular Accident Per Session NHIS", "Clinical Services", 1500),
    ("Physiotherapy Chest Conditions Per Session NHIS", "Clinical Services", 1500),
    ("Physiotherapy Diabetic Neuropathy NHIS", "Clinical Services", 1500),
    ("Physiotherapy Facial Bells Palsy NHIS", "Clinical Services", 1500),
    ("Physiotherapy Spinal Cord Lesion NHIS", "Clinical Services", 1500),
    ("Physiotherapy Parkinsonism NHIS", "Clinical Services", 1500),
    ("Physiotherapy Peripheral Nerve Injuries NHIS", "Clinical Services", 1500),
    ("Physiotherapy Sciatica NHIS", "Clinical Services", 1500),
    ("Physiotherapy Cerebral Palsy NHIS", "Clinical Services", 1500),
    ("Physiotherapy Arthritis Per Visit NHIS", "Clinical Services", 1500),
    ("Physiotherapy Low Back Pain Per Visit NHIS", "Clinical Services", 1500),
    ("Physiotherapy Burns NHIS", "Clinical Services", 1500),
    ("Physiotherapy Post Surgical Rehabilitation NHIS", "Clinical Services", 1500),
    ("Physiotherapy Fractures Dislocations NHIS", "Clinical Services", 1500),
    ("Physiotherapy Uterine Prolapse NHIS", "Clinical Services", 1500),

    # ── HYSTEROSCOPIC PROCEDURES ──────────────────────────────────────
    ("Ablation of Endometrium NHIS", "Clinical Services", 4000),
    ("Hysteroscopic Tubal Cannulation NHIS", "Clinical Services", 35000),
    ("Polypectomy Hysteroscopic NHIS", "Clinical Services", 35000),
    ("Uterine Synechia Cutting NHIS", "Clinical Services", 35000),

    # ── NEUROSURGERY ──────────────────────────────────────────────────
    ("Repair Transposition Nerve NHIS", "Clinical Services", 70000),
    ("Skull Traction NHIS", "Clinical Services", 70000),
    ("Carpal Tunnel Release NHIS", "Clinical Services", 70000),
    ("Cranioplasty NHIS", "Clinical Services", 70000),
    ("Lumbar Disc NHIS", "Clinical Services", 80000),
    ("Microdiscectomy Cervical Lumbar NHIS", "Clinical Services", 80000),
    ("Peripheral Nerve Surgery NHIS", "Clinical Services", 80000),
    ("Shunt Neurosurgery NHIS", "Clinical Services", 85000),
    ("Spine Canal Stenosis NHIS", "Clinical Services", 85000),
    ("Spine Disc Cervical Lumber NHIS", "Clinical Services", 85000),
    ("Burr Hole NHIS", "Clinical Services", 100000),
    ("Craniostenosis NHIS", "Clinical Services", 100000),
    ("Haematoma Brain Head Injuries NHIS", "Clinical Services", 100000),
    ("Laminectomy with Fusion NHIS", "Clinical Services", 100000),
    ("Spine Anterior Decompression NHIS", "Clinical Services", 100000),
    ("Spine Decompression Fusion NHIS", "Clinical Services", 100000),
    ("Tumours Supratentorial NHIS", "Clinical Services", 100000),
    ("Anneurysm NHIS", "Clinical Services", 120000),
    ("Anterior Encephalocele NHIS", "Clinical Services", 100000),
    ("Meningocele Lumbar NHIS", "Clinical Services", 100000),

    # ── RADIOLOGY - PLAIN X-RAYS UPPER LIMB ──────────────────────────
    ("X-Ray Hand Finger Adult NHIS", "Radiology", 1200),
    ("X-Ray Wrist Adult NHIS", "Radiology", 1200),
    ("X-Ray Forearm Adult NHIS", "Radiology", 1200),
    ("X-Ray Elbow Adult NHIS", "Radiology", 1200),
    ("X-Ray Humerus Adult NHIS", "Radiology", 1200),
    ("X-Ray Shoulder Adult NHIS", "Radiology", 1800),
    ("X-Ray Clavicle NHIS", "Radiology", 1800),

    # ── RADIOLOGY - LOWER LIMB ────────────────────────────────────────
    ("X-Ray Foot Toe Adult NHIS", "Radiology", 1200),
    ("X-Ray Ankle Adult NHIS", "Radiology", 1200),
    ("X-Ray Leg Tibia Fibula Adult NHIS", "Radiology", 1800),
    ("X-Ray Knee Adult NHIS", "Radiology", 1800),
    ("X-Ray Hip Adult NHIS", "Radiology", 1800),
    ("X-Ray Femur Thigh Adult NHIS", "Radiology", 1800),
    ("X-Ray Pelvic Adult NHIS", "Radiology", 1800),

    # ── RADIOLOGY - THORAX ────────────────────────────────────────────
    ("X-Ray Chest PA AP Adult NHIS", "Radiology", 1800),
    ("X-Ray Chest PA Lateral Adult NHIS", "Radiology", 1800),
    ("X-Ray Chest Ribs Oblique Adult NHIS", "Radiology", 1800),
    ("X-Ray Sternum NHIS", "Radiology", 1500),
    ("X-Ray Thoracic Inlet Adult NHIS", "Radiology", 1800),

    # ── RADIOLOGY - VERTEBRAE ─────────────────────────────────────────
    ("X-Ray Cervical Spine Adult NHIS", "Radiology", 2400),
    ("X-Ray Lateral Neck Soft Tissue NHIS", "Radiology", 2400),
    ("X-Ray Thoracic Spine NHIS", "Radiology", 2400),
    ("X-Ray Thoraco Lumber Spine Adult NHIS", "Radiology", 2800),
    ("X-Ray Lumbar Spine NHIS", "Radiology", 2400),
    ("X-Ray Lumbo Sacral Spine Adult NHIS", "Radiology", 2800),
    ("X-Ray Sacrum NHIS", "Radiology", 2400),
    ("X-Ray Sacro Iliac Joint NHIS", "Radiology", 2400),

    # ── RADIOLOGY - ABDOMEN & SKULL ───────────────────────────────────
    ("X-Ray Abdomen Plain NHIS", "Radiology", 1800),
    ("X-Ray Abdomen Erect Supine NHIS", "Radiology", 1800),
    ("X-Ray Skull AP Lat NHIS", "Radiology", 2400),
    ("X-Ray Skull PA Lat Townes NHIS", "Radiology", 2400),
    ("X-Ray Mastoids Owens Townes NHIS", "Radiology", 2400),
    ("X-Ray Sinuses AP LNT OM NHIS", "Radiology", 3000),
    ("X-Ray Mandibles Jaw NHIS", "Radiology", 2400),
    ("X-Ray Paranasal Sinuses NHIS", "Radiology", 2150),

    # ── RADIOLOGY - SPECIAL INVESTIGATIONS ───────────────────────────
    ("Barium Swallow NHIS", "Radiology", 10000),
    ("Barium Meal Follow Through NHIS", "Radiology", 15000),
    ("Barium Enema NHIS", "Radiology", 14000),
    ("Intravenous Urography IVU NHIS", "Radiology", 15250),
    ("Hysterosalpingogram HSG NHIS", "Radiology", 12250),
    ("Cysto-Urethrogram NHIS", "Radiology", 12250),
    ("Fistulogram NHIS", "Radiology", 9850),
    ("Myelogram NHIS", "Radiology", 40000),
    ("Skeletal Survey Adult NHIS", "Radiology", 6250),
    ("MRI Scan Adult NHIS", "Radiology", 70000),
    ("MRI Scan Children NHIS", "Radiology", 35000),
    ("CT Scan Adult NHIS", "Radiology", 60000),
    ("CT Scan Children NHIS", "Radiology", 30000),
    ("Mammogram NHIS", "Radiology", 8850),
    ("Radiotherapy Radical Per Session NHIS", "Clinical Services", 25000),
    ("Radiotherapy Palliative Per Session NHIS", "Clinical Services", 25000),
    ("Bone Scan NHIS", "Radiology", 20000),
    ("Renal Scan DTPA DMSA NHIS", "Radiology", 15000),

    # ── ULTRASOUND ────────────────────────────────────────────────────
    ("Obstetric Scan Ultrasound NHIS", "Radiology", 3550),
    ("Abdominal Scan Ultrasound NHIS", "Radiology", 3550),
    ("Pelvic Scan Ultrasound NHIS", "Radiology", 3550),
    ("Breast Scan Ultrasound NHIS", "Radiology", 3950),
    ("Bladder Scan Ultrasound NHIS", "Radiology", 3950),
    ("Abdominal Pelvic Scan Ultrasound NHIS", "Radiology", 3950),
    ("Prostate Scan Ultrasound NHIS", "Radiology", 3950),
    ("Thyroid Scan Ultrasound NHIS", "Radiology", 3950),
    ("Testes Scrotal Scan Ultrasound NHIS", "Radiology", 3950),
    ("Transvaginal Scan Ovulometry NHIS", "Radiology", 3950),
    ("Doppler Scan NHIS", "Radiology", 5000),
    ("Ocular Scan NHIS", "Radiology", 5000),

    # ── LABORATORY - PRIMARY HEALTHCARE ──────────────────────────────
    ("PCV Lab Primary NHIS", "Laboratory", 600),
    ("Haemoglobin HB Lab Primary NHIS", "Laboratory", 600),
    ("White Cell Count WBC NHIS", "Laboratory", 600),
    ("Differential WBC Count NHIS", "Laboratory", 650),
    ("ESR Lab Primary NHIS", "Laboratory", 450),
    ("Blood Film Malaria Parasites MP Primary NHIS", "Laboratory", 450),
    ("Widal Test Lab Primary NHIS", "Laboratory", 700),
    ("Blood Grouping ABO Rh Primary NHIS", "Laboratory", 500),
    ("VDRL Lab Primary NHIS", "Laboratory", 700),
    ("Urine Microscopy Primary NHIS", "Laboratory", 400),
    ("Urinalysis Lab Primary NHIS", "Laboratory", 400),
    ("Pregnancy Test Urine Primary NHIS", "Laboratory", 400),
    ("Stool Analysis RE Only NHIS", "Laboratory", 400),
    ("Blood Sugar FBS RBS Primary NHIS", "Laboratory", 650),
    ("HB Genotype Lab Primary NHIS", "Laboratory", 850),

    # ── LABORATORY - CLINICAL CHEMISTRY SECONDARY ─────────────────────
    ("Full Electrolytes Lab Secondary NHIS", "Laboratory", 1800),
    ("Sodium Lab NHIS", "Laboratory", 450),
    ("Potassium Lab NHIS", "Laboratory", 450),
    ("Urea Lab Secondary NHIS", "Laboratory", 600),
    ("Creatinine Lab Secondary NHIS", "Laboratory", 600),
    ("Liver Function Tests Secondary NHIS", "Laboratory", 2750),
    ("Total Protein Lab NHIS", "Laboratory", 650),
    ("Albumin Lab Secondary NHIS", "Laboratory", 650),
    ("Total Cholesterol Lab NHIS", "Laboratory", 850),
    ("Total Lipid Profile Lab NHIS", "Laboratory", 3400),
    ("Amylase Lab NHIS", "Laboratory", 750),
    ("Fasting Blood Sugar FBS Secondary NHIS", "Laboratory", 500),
    ("Random Blood Sugar RBS Secondary NHIS", "Laboratory", 500),
    ("2Hr Post Prandial Blood Sugar NHIS", "Laboratory", 800),
    ("Oral Glucose Tolerance Test OGTT NHIS", "Laboratory", 1800),
    ("Uric Acid Lab Secondary NHIS", "Laboratory", 600),
    ("Magnesium Lab Secondary NHIS", "Laboratory", 700),
    ("Creatine Phosphokinase CPK NHIS", "Laboratory", 1200),
    ("Lactate Dehydrogenase LDH NHIS", "Laboratory", 820),
    ("Urinalysis Lab Secondary NHIS", "Laboratory", 400),
    ("Creatinine Clearance NHIS", "Laboratory", 900),
    ("Glycocylated Haemoglobin HBA1C Secondary NHIS", "Laboratory", 1200),
    ("Pregnancy Test Blood NHIS", "Laboratory", 700),
    ("Calcium Lab NHIS", "Laboratory", 700),
    ("Troponin T NHIS", "Laboratory", 5000),
    ("FSH Follicle Stimulating Hormone NHIS", "Laboratory", 4700),
    ("LH Luteinizing Hormone NHIS", "Laboratory", 4700),
    ("Prolactin Lab NHIS", "Laboratory", 4700),
    ("Progesterone Lab NHIS", "Laboratory", 4700),
    ("Testosterone Lab NHIS", "Laboratory", 4700),
    ("Oestradiol E2 Lab NHIS", "Laboratory", 4700),
    ("Cortisol Lab NHIS", "Laboratory", 4700),
    ("T3 Triiodothyronine NHIS", "Laboratory", 4950),
    ("T4 Thyroxine NHIS", "Laboratory", 4950),
    ("TSH Thyroid Stimulating Hormone NHIS", "Laboratory", 4950),
    ("CEA Carcinoembryonic Antigen NHIS", "Laboratory", 5000),
    ("CA 125 Ovarian Cancer Antigen NHIS", "Laboratory", 5000),
    ("AFP Alpha Feto Protein Secondary NHIS", "Laboratory", 3950),
    ("PSA Total Prostate Specific Antigen NHIS", "Laboratory", 9250),
    ("PSA Free Prostate Specific Antigen NHIS", "Laboratory", 5550),

    # ── LABORATORY - HAEMATOLOGY ──────────────────────────────────────
    ("Full Blood Count FBC All Parameters NHIS", "Laboratory", 2600),
    ("Haemoglobin HB Secondary NHIS", "Laboratory", 600),
    ("PCV Secondary NHIS", "Laboratory", 600),
    ("ESR Secondary NHIS", "Laboratory", 400),
    ("Prothrombin Time PT NHIS", "Laboratory", 1200),
    ("HB Genotype Secondary NHIS", "Laboratory", 850),
    ("Blood Grouping ABO RH Secondary NHIS", "Laboratory", 500),
    ("Sickling Test NHIS", "Laboratory", 500),
    ("Cross Match NHIS", "Laboratory", 600),
    ("G-6-PD Screening NHIS", "Laboratory", 2350),
    ("Coagulation Profile NHIS", "Laboratory", 5950),
    ("Bone Marrow Examination NHIS", "Laboratory", 5000),
    ("Fibrinogen Lab NHIS", "Laboratory", 3850),
    ("Blood Gas Analysis NHIS", "Laboratory", 5950),
    ("D-Dimer NHIS", "Laboratory", 4950),
    ("Ferritin NHIS", "Laboratory", 1850),
    ("Vitamin D Lab NHIS", "Laboratory", 3850),
    ("Vitamin B12 Lab NHIS", "Laboratory", 3850),

    # ── LABORATORY - MICROBIOLOGY ─────────────────────────────────────
    ("Urine Microscopy Culture Sensitivity NHIS", "Laboratory", 1000),
    ("Stool Microscopy RE Only Secondary NHIS", "Laboratory", 500),
    ("Stool Microscopy Culture Sensitivity NHIS", "Laboratory", 1000),
    ("Faecal Occult Blood NHIS", "Laboratory", 650),
    ("H. Pylori Lab Secondary NHIS", "Laboratory", 2000),
    ("Blood Culture Sensitivity NHIS", "Laboratory", 2000),
    ("Malaria Parasites Secondary NHIS", "Laboratory", 450),
    ("Semen Analysis NHIS", "Laboratory", 1250),
    ("Sputum ZN Stain AFB NHIS", "Laboratory", 1200),
    ("Sputum Culture Sensitivity NHIS", "Laboratory", 1000),
    ("Swabs Culture Sensitivity NHIS", "Laboratory", 1000),
    ("Mantoux Test NHIS", "Laboratory", 950),

    # ── LABORATORY - SEROLOGY ─────────────────────────────────────────
    ("Widal Test Secondary NHIS", "Laboratory", 700),
    ("VDRL Secondary NHIS", "Laboratory", 700),
    ("Rheumatoid Factor Secondary NHIS", "Laboratory", 600),
    ("Hepatitis B Surface Antigen HbsAg NHIS", "Laboratory", 1000),
    ("Hepatitis B Confirmatory Test Core Antigen NHIS", "Laboratory", 3000),
    ("HCV Hepatitis C Antigen NHIS", "Laboratory", 3500),
    ("Hepatitis B DNA Viral Load NHIS", "Laboratory", 20000),
    ("HIV Screening NHIS", "Laboratory", 1750),
    ("HIV Confirmatory Test NHIS", "Laboratory", 4850),
    ("CD4 Count Secondary NHIS", "Laboratory", 4150),
    ("HIV Viral Load NHIS", "Laboratory", 5550),
    ("Hepatitis C RNA Viral Load NHIS", "Laboratory", 11500),
    ("Serum Tuberculosis Antigen NHIS", "Laboratory", 2500),
    ("Chlamydia Antigen NHIS", "Laboratory", 2500),
    ("Helicobacter Pylori Secondary NHIS", "Laboratory", 2000),
    ("C-Reactive Protein NHIS", "Laboratory", 2650),
    ("Cytomegalovirus CMV Qualitative NHIS", "Laboratory", 3250),

    # ── LABORATORY - HISTOLOGY ────────────────────────────────────────
    ("Tissue Biopsy Small NHIS", "Laboratory", 5250),
    ("Tissue Biopsy Multiple NHIS", "Laboratory", 7150),
    ("Lymph Nodes Biopsy NHIS", "Laboratory", 5250),
    ("Pap Smear Secondary NHIS", "Laboratory", 4000),
    ("Fine Needle Aspiration FNA NHIS", "Laboratory", 4200),
]

created = 0
updated = 0
svc_created = 0

for name, category, price in services:
    svc, was_new = Service.objects.update_or_create(
        name=name,
        defaults={"category": category, "price": price, "is_active": True}
    )
    if was_new:
        svc_created += 1

    _, was_created = ServiceTariff.objects.update_or_create(
        service=svc,
        patient_type='retainership',
        hmo=hmo,
        defaults={"price": price, "is_active": True}
    )
    if was_created:
        created += 1
    else:
        updated += 1

print(f"\nNew services created:  {svc_created}")
print(f"NHIS Tariffs created:  {created}")
print(f"NHIS Tariffs updated:  {updated}")
print(f"Total tariffs set:     {created + updated}")
print(f"\nDone! NHIS Professional FFS tariffs are now live.")
