import os
import django
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'dannys_wellness.settings')
django.setup()

from billing.models import Service, ServiceTariff
from patients.models import HMO

try:
    hmo = HMO.objects.get(name__icontains='NHIA')
    print(f"HMO: {hmo.name} ({hmo.code})")
except HMO.DoesNotExist:
    print("ERROR: NHIA HMO not found. Add it first via /dashboard/admin/hmos")
    exit()

# NHIS Medicines Price List October 2021
# Format: (Medicine Name, Category, Price in Naira)
services = [
    # ANAESTHETICS
    ("Halothane Inhalation", "Pharmacy", 67),
    ("Ketamine Injection", "Pharmacy", 1171),
    ("Nitrous Oxide", "Pharmacy", 5000),
    ("Oxygen Per Hour", "Clinical Services", 500),
    ("Thiopental Injection", "Pharmacy", 3572),
    ("Atropine Injection 0.5mg", "Pharmacy", 59),
    ("Atropine Injection 1mg", "Pharmacy", 59),
    ("Diazepam Injection 5mg", "Pharmacy", 177),
    ("Hyoscine N-Butylbromide Injection", "Pharmacy", 65),
    ("Midazolam 15mg Injection", "Pharmacy", 2600),
    ("Morphine Injection 10mg", "Pharmacy", 236),
    ("Morphine Injection 25mg", "Pharmacy", 354),
    ("Promethazine Tablets 5mg", "Pharmacy", 6),
    ("Promethazine Syrup", "Pharmacy", 200),
    ("Promethazine Injection 2ml", "Pharmacy", 30),
    ("Glycopyrollate 0.2mg Injection", "Pharmacy", 240),
    ("Atracurium Injection", "Pharmacy", 2400),
    ("Edrophonium Injection", "Pharmacy", 1150),
    ("Neostigmine Injection", "Pharmacy", 288),
    ("Pancuronium Injection 4mg", "Pharmacy", 632),
    ("Suxamethonium Injection", "Pharmacy", 2548),
    ("Propofol 1% Injection", "Pharmacy", 2500),
    ("Lidocaine Injection 1%/2%", "Pharmacy", 470),
    ("Bupivacaine Injection", "Pharmacy", 590),
    ("Lidocaine Topical Spray", "Pharmacy", 1500),
    ("Lidocaine Jelly", "Pharmacy", 900),
    # ANALGESICS
    ("Morphine Injection 10mg/1ml", "Pharmacy", 690),
    ("Morphine Injection 15mg/1ml", "Pharmacy", 870),
    ("Morphine Tablet 30mg", "Pharmacy", 200),
    ("Pentazocine Injection", "Pharmacy", 200),
    ("Pethidine Injection", "Pharmacy", 250),
    ("Tramadol Tablet 50mg", "Pharmacy", 70),
    ("Tramadol Injection 50mg", "Pharmacy", 373),
    ("Morphine 1mg/ml Syrup 200ml", "Pharmacy", 1000),
    ("Morphine 1mg/ml Syrup 500ml", "Pharmacy", 1500),
    ("Codeine/Paracetamol 8/500mg", "Pharmacy", 65),
    ("Codeine/Paracetamol 30/500mg", "Pharmacy", 100),
    ("Naloxone Injection", "Pharmacy", 910),
    ("Paracetamol Tablets 500mg", "Pharmacy", 3),
    ("Paracetamol Suppository", "Pharmacy", 25),
    ("Paracetamol Syrup 125mg/5ml", "Pharmacy", 200),
    ("Paracetamol Injection 150mg/ml", "Pharmacy", 30),
    ("Allopurinol Tablet 100mg", "Pharmacy", 31),
    ("Allopurinol Tablet 300mg", "Pharmacy", 55),
    ("Celecoxib Capsules 200mg", "Pharmacy", 240),
    ("Diclofenac Tablet 100mg", "Pharmacy", 30),
    ("Diclofenac Tablet 50mg", "Pharmacy", 20),
    ("Diclofenac Injection 25mg", "Pharmacy", 50),
    ("Diclofenac Sodium Gel 1%", "Pharmacy", 500),
    ("Ibuprofen Tablets 200mg", "Pharmacy", 15),
    ("Ibuprofen Tablets 400mg", "Pharmacy", 25),
    ("Ibuprofen Suspension 100mg", "Pharmacy", 250),
    ("Ketoprofen Capsules 200mg", "Pharmacy", 92),
    ("Ketoprofen Injection 100mg", "Pharmacy", 154),
    ("Naproxen Tablet 250mg", "Pharmacy", 25),
    ("Naproxen Tablet 500mg", "Pharmacy", 30),
    ("Piroxicam Capsules 20mg", "Pharmacy", 25),
    ("Piroxicam Injection 10mg", "Pharmacy", 50),
    ("Meloxicam 15mg Capsule", "Pharmacy", 90),
    ("Meloxicam 7.5mg Capsule", "Pharmacy", 60),
    ("Diclofenac 100mg Suppository", "Pharmacy", 350),
    ("Aceclofenac Tablet 100mg", "Pharmacy", 20),
    # ANTI-ALLERGICS
    ("Cetrizine Tablet 10mg", "Pharmacy", 30),
    ("Cetrizine Syrup 1mg/5ml", "Pharmacy", 850),
    ("Chlorpheniramine Tablet 4mg", "Pharmacy", 5),
    ("Chlorpheniramine Syrup 2mg/5ml", "Pharmacy", 280),
    ("Chlorpheniramine Injection 10mg", "Pharmacy", 30),
    ("Loratidine Tablet 10mg", "Pharmacy", 34),
    ("Loratidine Syrup 5mg/5ml", "Pharmacy", 620),
    ("Promethazine Tablets 25mg", "Pharmacy", 3),
    ("Promethazine Syrup 5mg/5ml", "Pharmacy", 250),
    ("Promethazine Injection 25mg/ml", "Pharmacy", 40),
    ("Dexamethasone Injection 4mg", "Pharmacy", 30),
    ("Hydrocortisone Injection 100mg", "Pharmacy", 290),
    # ANTI-CONVULSANTS
    ("Carbamazepine Tablet 200mg", "Pharmacy", 20),
    ("Carbamazepine Tablet 400mg", "Pharmacy", 30),
    ("Carbamazepine Syrup 100mg/5ml", "Pharmacy", 3855),
    ("Diazepam Injection 5mg/2ml", "Pharmacy", 300),
    ("Magnesium Sulphate Injection 50%", "Pharmacy", 290),
    ("Phenobarbital Tablets 15mg", "Pharmacy", 9),
    ("Phenobarbital Tablets 30mg", "Pharmacy", 13),
    ("Phenobarbital Syrup 15mg/5ml", "Pharmacy", 528),
    ("Phenobarbital Injection 200mg", "Pharmacy", 300),
    ("Phenytoin Sodium Capsule 100mg", "Pharmacy", 38),
    ("Sodium Valproate Tablets 200mg", "Pharmacy", 39),
    ("Sodium Valproate Tablets 500mg", "Pharmacy", 90),
    ("Pregabalin Tablet 75mg", "Pharmacy", 90),
    ("Pregabalin Tablet 150mg", "Pharmacy", 120),
    # ANTI-INFECTIVES
    ("Metronidazole Tablets 200mg", "Pharmacy", 6),
    ("Metronidazole Tablet 400mg", "Pharmacy", 10),
    ("Metronidazole Suspension 200mg", "Pharmacy", 230),
    ("Metronidazole IV Injection 500mg", "Pharmacy", 200),
    ("Metronidazole Suppository 500mg", "Pharmacy", 150),
    ("Albendazole Tablet 200mg", "Pharmacy", 100),
    ("Albendazole Suspension Oral", "Pharmacy", 100),
    ("Mebendazole Tablet 100mg", "Pharmacy", 350),
    ("Mebendazole Suspension", "Pharmacy", 400),
    ("Artesunate 120mg Injection", "Pharmacy", 883),
    ("Artesunate 30mg Injection", "Pharmacy", 466),
    ("Artesunate 60mg Injection", "Pharmacy", 550),
    ("Artemether + Lumefantrine 80/480mg", "Pharmacy", 700),
    ("Artemether + Lumefantrine 20/120mg", "Pharmacy", 400),
    ("Artemether + Lumefantrine Suspension", "Pharmacy", 380),
    ("Chloroquine Tablet", "Pharmacy", 20),
    ("Chloroquine Injection", "Pharmacy", 70),
    ("Chloroquine Syrup", "Pharmacy", 250),
    ("Pyrimethamine + Sulphadoxine", "Pharmacy", 200),
    ("Quinine Tablet 300mg", "Pharmacy", 50),
    ("Quinine Injection 300mg", "Pharmacy", 150),
    ("Amikacin 500mg Injection", "Pharmacy", 700),
    ("Amoxycillin Capsule 250mg", "Pharmacy", 20),
    ("Amoxycillin Capsule 500mg", "Pharmacy", 30),
    ("Amoxycillin Suspension 125mg/5ml", "Pharmacy", 330),
    ("Amoxycillin Injection 500mg", "Pharmacy", 200),
    ("Amoxycillin + Clavulanic Acid 250mg Tab", "Pharmacy", 95),
    ("Amoxycillin + Clavulanic Acid 500mg Tab", "Pharmacy", 100),
    ("Amoxicillin + Clavulanic Acid 1g Tablet", "Pharmacy", 120),
    ("Amoxycillin + Clavulanic Acid Injection 500mg", "Pharmacy", 1000),
    ("Amoxycillin + Clavulanic Acid Injection 1g", "Pharmacy", 1200),
    ("Azithromycin Capsules 250mg", "Pharmacy", 125),
    ("Azithromycin Capsules 500mg", "Pharmacy", 500),
    ("Azithromycin Suspension 200mg/5ml", "Pharmacy", 750),
    ("Ceftriaxone Injection 250mg", "Pharmacy", 500),
    ("Ceftriaxone Injection 500mg", "Pharmacy", 500),
    ("Ceftriaxone Injection 1g IV", "Pharmacy", 500),
    ("Cefuroxime Tablets 250mg", "Pharmacy", 150),
    ("Cefuroxime Tablets 500mg", "Pharmacy", 180),
    ("Cefuroxime Suspension 125mg/5ml", "Pharmacy", 1000),
    ("Cefuroxime Injection 750mg", "Pharmacy", 450),
    ("Ciprofloxacin Tablet 250mg", "Pharmacy", 40),
    ("Ciprofloxacin Tablet 500mg", "Pharmacy", 40),
    ("Ciprofloxacin Infusion IV 2mg/ml", "Pharmacy", 200),
    ("Clarithromycin Tablet 250mg", "Pharmacy", 125),
    ("Clarithromycin Tablet 500mg", "Pharmacy", 180),
    ("Clarithromycin Suspension 125mg", "Pharmacy", 880),
    ("Clindamycin Capsule 150mg", "Pharmacy", 75),
    ("Clindamycin Injection 150mg/ml", "Pharmacy", 600),
    ("Co-trimoxazole Tablet 400/80mg", "Pharmacy", 5),
    ("Co-trimoxazole Tablet 800/160mg", "Pharmacy", 10),
    ("Co-trimoxazole Suspension", "Pharmacy", 180),
    ("Doxycycline Capsule 100mg", "Pharmacy", 20),
    ("Erythromycin Tablet 250mg", "Pharmacy", 15),
    ("Erythromycin Tablet 500mg", "Pharmacy", 50),
    ("Erythromycin Suspension 125mg/5ml", "Pharmacy", 400),
    ("Gentamycin Injection 80mg", "Pharmacy", 155),
    ("Levofloxacin Tablet 250mg", "Pharmacy", 60),
    ("Levofloxacin Tablet 500mg", "Pharmacy", 70),
    ("Levofloxacin Tablet 750mg", "Pharmacy", 100),
    ("Levofloxacin Injection 500mg/100ml", "Pharmacy", 784),
    ("Ofloxacin Tablet 200mg", "Pharmacy", 50),
    ("Tetracycline Capsule 250mg", "Pharmacy", 20),
    ("Vancomycin Injection", "Pharmacy", 900),
    ("Fluconazole Capsule 50mg", "Pharmacy", 60),
    ("Fluconazole Capsule 150mg", "Pharmacy", 60),
    ("Fluconazole Capsule 200mg", "Pharmacy", 225),
    ("Fluconazole Suspension 50mg/5ml", "Pharmacy", 1000),
    ("Fluconazole Injection IV 2mg/ml", "Pharmacy", 350),
    ("Ketoconazole Tablet 200mg", "Pharmacy", 22),
    ("Nystatin Tablet 500,000 units", "Pharmacy", 40),
    ("Nystatin Suspension 100,000 units/ml", "Pharmacy", 380),
    ("Aciclovir Tablets 200mg", "Pharmacy", 153),
    ("Aciclovir Tablets 400mg", "Pharmacy", 268),
    ("Aciclovir Cream 5%", "Pharmacy", 531),
    ("Tenofovir 300mg Tablet", "Pharmacy", 108),
    # BLOOD DRUGS
    ("Ferrous Sulphate Tablets 200mg", "Pharmacy", 4),
    ("Folic Acid Tablet 5mg", "Pharmacy", 4),
    ("Heparin Sodium Injection 5000 units", "Pharmacy", 732),
    ("Warfarin Sodium Tablets 3mg", "Pharmacy", 35),
    ("Warfarin Sodium Tablets 5mg", "Pharmacy", 35),
    ("Tranexamic Acid 500mg Injection", "Pharmacy", 285),
    # CARDIOVASCULAR
    ("Atenolol Tablet 25mg", "Pharmacy", 16),
    ("Atenolol Tablet 50mg", "Pharmacy", 18),
    ("Atenolol Tablet 100mg", "Pharmacy", 30),
    ("Glyceryl Trinitrate Tablet", "Pharmacy", 100),
    ("Isosorbide Dinitrate Tablet 5mg", "Pharmacy", 25),
    ("Isosorbide Dinitrate Tablet 10mg", "Pharmacy", 40),
    ("Propranolol Tablet 40mg", "Pharmacy", 40),
    ("Propranolol Injection 1mg/ml", "Pharmacy", 200),
    ("Bisoprolol 2.5mg Tablet", "Pharmacy", 30),
    ("Bisoprolol 5mg Tablet", "Pharmacy", 30),
    ("Amiodarone Tab 200mg", "Pharmacy", 54),
    ("Frusemide Tablet 40mg", "Pharmacy", 8),
    ("Frusemide Injection 10mg/ml", "Pharmacy", 50),
    ("Hydrochlorothiazide Tablet 25mg", "Pharmacy", 6),
    ("Spironolactone Tablet 25mg", "Pharmacy", 5),
    ("Spironolactone Tablet 50mg", "Pharmacy", 27),
    ("Amlodipine Tablet 5mg", "Pharmacy", 20),
    ("Amlodipine Tablet 10mg", "Pharmacy", 22),
    ("Captopril Tablet 12.5mg", "Pharmacy", 15),
    ("Captopril Tablet 25mg", "Pharmacy", 20),
    ("Captopril Tablet 50mg", "Pharmacy", 57),
    ("Enalapril Tablet 5mg", "Pharmacy", 30),
    ("Enalapril Tablet 10mg", "Pharmacy", 35),
    ("Hydralazine Tablet 25mg", "Pharmacy", 15),
    ("Hydralazine Tablet 50mg", "Pharmacy", 25),
    ("Lisinopril Tablet 5mg", "Pharmacy", 25),
    ("Lisinopril Tablet 10mg", "Pharmacy", 32),
    ("Losartan 50mg Tablet", "Pharmacy", 60),
    ("Methyldopa Tablet 500mg", "Pharmacy", 50),
    ("Nifedipine Tablet 20mg", "Pharmacy", 33),
    ("Digoxin Tablets 0.25mg", "Pharmacy", 31),
    ("Digoxin Injection 0.25mg/ml", "Pharmacy", 300),
    ("Dopamine Injection 40mg/ml", "Pharmacy", 400),
    ("Atorvastatin Tablet 10mg", "Pharmacy", 54),
    ("Atorvastatin Tablet 20mg", "Pharmacy", 80),
    ("Simvastatin Tablet 10mg", "Pharmacy", 21),
    ("Simvastatin Tablet 20mg", "Pharmacy", 38),
    # GASTROINTESTINAL
    ("Metoclopramide Tablet 10mg", "Pharmacy", 8),
    ("Metoclopramide Injection 5mg/ml", "Pharmacy", 35),
    ("Hyoscine N-Butylbromide Tablet 10mg", "Pharmacy", 12),
    ("Hyoscine N-Butylbromide Injection 20mg", "Pharmacy", 59),
    ("Bisacodyl Tablet 5mg", "Pharmacy", 6),
    ("Loperamide Tablet 2mg", "Pharmacy", 19),
    ("Oral Rehydration Salt Sachet", "Pharmacy", 50),
    ("Cimetidine Tablets 200mg", "Pharmacy", 12),
    ("Cimetidine Tablets 400mg", "Pharmacy", 18),
    ("Omeprazole Tablet 20mg", "Pharmacy", 39),
    ("Ranitidine Tablets 150mg", "Pharmacy", 19),
    ("Ranitidine Tablets 300mg", "Pharmacy", 35),
    ("Ranitidine Injection 25mg/ml", "Pharmacy", 260),
    ("Esomeprazole Tablet 20mg", "Pharmacy", 41),
    ("Esomeprazole 40mg Tablet", "Pharmacy", 600),
    # HORMONES
    ("Dexamethasone Tablets 0.5mg", "Pharmacy", 10),
    ("Dexamethasone Injection 4mg/ml", "Pharmacy", 24),
    ("Hydrocortisone Injection Powder 100mg", "Pharmacy", 177),
    ("Prednisolone Tablets 5mg", "Pharmacy", 10),
    ("Metformin Tablets 500mg", "Pharmacy", 14),
    ("Metformin Tablets 850mg", "Pharmacy", 53),
    ("Metformin Tablets 1000mg", "Pharmacy", 18),
    ("Glibenclamide Tablets 5mg", "Pharmacy", 15),
    ("Glimepiride Tablet 1mg", "Pharmacy", 30),
    ("Glimepiride Tablet 2mg", "Pharmacy", 38),
    ("Glimepiride Tablet 4mg", "Pharmacy", 67),
    ("Insulin Soluble Injection 100 units/ml", "Pharmacy", 4805),
    ("Carbimazole Tablets 5mg", "Pharmacy", 19),
    ("Levothyroxine Tablets 0.1mg", "Pharmacy", 59),
    # VITAMINS & MINERALS
    ("Folic Acid Tablet 5mg NHIA", "Pharmacy", 3),
    ("Multivitamin Tablet", "Pharmacy", 5),
    ("Multivitamin Syrup 100mls", "Pharmacy", 200),
    ("Ascorbic Acid Tablets 100mg", "Pharmacy", 3),
    ("Ferrous Sulphate Tablets 60mg Iron", "Pharmacy", 4),
    ("Vitamin B Complex Tablets", "Pharmacy", 5),
    ("Vitamin B Complex Syrup 100ml", "Pharmacy", 200),
    ("Vitamin B Complex Injection", "Pharmacy", 200),
    ("Calcium Gluconate Tablets 600mg", "Pharmacy", 5),
    ("Zinc 20mg Dispersible Tablet", "Pharmacy", 10),
    # CONSUMABLES (NHIA covered)
    ("Blood Giving Set NHIA", "Consumables", 300),
    ("IV Cannula NHIA", "Consumables", 150),
    ("Foley Catheter NHIA", "Consumables", 600),
    ("NG Tube NHIA", "Consumables", 170),
    ("Scalp Vein Needle NHIA", "Consumables", 50),
    ("Surgical Gloves NHIA", "Consumables", 100),
    ("Syringe 2ml NHIA", "Consumables", 50),
    ("Syringe 5ml NHIA", "Consumables", 50),
    ("Syringe 10ml NHIA", "Consumables", 50),
    ("Urine Bag NHIA", "Consumables", 300),
    ("Infusion Set NHIA", "Consumables", 150),
    # IV FLUIDS
    ("Dextrose 5% IVF 500ml", "Pharmacy", 400),
    ("Dextrose 50% IVF 500ml", "Pharmacy", 400),
    ("Normal Saline 0.9% IVF", "Pharmacy", 400),
    ("Dextrose + Sodium Chloride IVF 5%/0.9%", "Pharmacy", 400),
    ("Glucose + Sodium Chloride Paediatric IVF", "Pharmacy", 400),
    ("Ringer's Lactate Solution IVF", "Pharmacy", 400),
    ("Sodium Lactate Compound IVF", "Pharmacy", 400),
    ("Mannitol Infusion 10%", "Pharmacy", 400),
    ("Mannitol Infusion 20%", "Pharmacy", 400),
    # LABORATORY (NHIA covered tests)
    ("MP Test NHIA", "Laboratory", 1000),
    ("Widal Test NHIA", "Laboratory", 2000),
    ("PCV Test NHIA", "Laboratory", 1000),
    ("Urinalysis NHIA", "Laboratory", 1000),
    ("PT Pregnancy Test NHIA", "Laboratory", 1000),
    ("HCV Test NHIA", "Laboratory", 1000),
    ("HBV Test NHIA", "Laboratory", 2000),
    ("FBC Test NHIA", "Laboratory", 1000),
    ("ESR Test NHIA", "Laboratory", 1500),
    ("Blood Grouping NHIA", "Laboratory", 1000),
    ("RBS Test NHIA", "Laboratory", 1000),
    ("FBS Test NHIA", "Laboratory", 1000),
    ("Urine MCS NHIA", "Laboratory", 2500),
    ("Stool MCS NHIA", "Laboratory", 2000),
    ("HbA1C Test NHIA", "Laboratory", 7000),
    ("Lipid Profile NHIA", "Laboratory", 2500),
    ("Genotype Test NHIA", "Laboratory", 4000),
    ("Urea Test NHIA", "Laboratory", 2500),
    ("Creatinine Test NHIA", "Laboratory", 2500),
    ("Cholesterol Test NHIA", "Laboratory", 2500),
    ("Albumin Test NHIA", "Laboratory", 2000),
    ("ALT Test NHIA", "Laboratory", 2000),
    ("LFT Test NHIA", "Laboratory", 8000),
    ("E/U/CR Test NHIA", "Laboratory", 9000),
    ("Electrolyte Test NHIA", "Laboratory", 3500),
    ("Blood Culture NHIA", "Laboratory", 3500),
    ("CD4 Count Test NHIA", "Laboratory", 3000),
    ("VDRL Test NHIA", "Laboratory", 1000),
    ("HVS MCS Test NHIA", "Laboratory", 7000),
    # CLINICAL SERVICES NHIA
    ("Echocardiography NHIA", "Clinical Services", 12000),
    ("ECG NHIA", "Clinical Services", 5000),
    ("Wound Dressing NHIA", "Clinical Services", 1500),
    ("Pelvic Scan NHIA", "Clinical Services", 3000),
    ("Obstetric Scan NHIA", "Clinical Services", 3000),
    ("Delivery NHIA", "Clinical Services", 12000),
    ("Anti Natal NHIA", "Clinical Services", 15000),
    # PSYCHOTROPIC
    ("Diazepam Tablets 5mg", "Pharmacy", 45),
    ("Lorazepam Tablets 1mg", "Pharmacy", 10),
    ("Amitriptyline Tablets 25mg", "Pharmacy", 9),
    ("Haloperidol Tablet 2mg", "Pharmacy", 20),
    ("Haloperidol Injection 5mg/ml", "Pharmacy", 150),
    ("Chlorpromazine Tablets 25mg", "Pharmacy", 10),
    ("Chlorpromazine Injection 25mg/ml", "Pharmacy", 118),
    # RESPIRATORY
    ("Aminophylline Injection 25mg/ml", "Pharmacy", 100),
    ("Salbutamol Tablets 2mg/4mg", "Pharmacy", 10),
    ("Salbutamol Syrup 2mg/5ml", "Pharmacy", 400),
    ("Salbutamol Aerosol 0.1mg", "Pharmacy", 1700),
    ("Salbutamol Injection 500ug/ml", "Pharmacy", 450),
    ("Theophylline Tablet 125mg", "Pharmacy", 20),
    ("Theophylline Tablet 250mg SR", "Pharmacy", 40),
    ("Beclomethasone Aerosol Inhalation", "Pharmacy", 2300),
    # VACCINES
    ("Tetanus Vaccine 0.5ml", "Clinical Services", 150),
    ("Hepatitis B Vaccine Injection", "Clinical Services", 2550),
    ("Measles Mumps Rubella Vaccine", "Clinical Services", 2850),
    # OXYTOCICS
    ("Ergometrine Tablet 0.5mg", "Pharmacy", 10),
    ("Ergometrine Injection 0.5mg/ml", "Pharmacy", 400),
    ("Oxytocin Injection 10 units/ml", "Pharmacy", 400),
    ("Misoprostol Tablet 200mcg", "Pharmacy", 125),
    # CYTOTOXICS (partial coverage)
    ("Ondansetron Injection 8mg", "Pharmacy", 850),
    ("Ondansetron Tablet 4mg", "Pharmacy", 46),
    ("Tamoxifen Tablet 20mg", "Pharmacy", 67),
    ("Hydroxyurea Tablet", "Pharmacy", 70),
]

created = 0
updated = 0
svc_created = 0

for name, category, price in services:
    svc, was_new_svc = Service.objects.update_or_create(
        name=name,
        defaults={"category": category, "price": price, "is_active": True}
    )
    if was_new_svc:
        svc_created += 1

    _, was_created = ServiceTariff.objects.update_or_create(
        service=svc,
        patient_type='retainership',
        hmo=hmo,
        defaults={"price": price, "is_active": True}
    )
    if was_created:
        created += 1
    else:
        updated += 1

print(f"\nServices created: {svc_created}")
print(f"NHIA Tariffs created: {created}")
print(f"NHIA Tariffs updated: {updated}")
print(f"Total tariffs: {created + updated}")
print("\nDone! NHIA tariffs are now live.")
