import os
import django
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'dannys_wellness.settings')
django.setup()

from billing.models import Service, ServiceTariff
from patients.models import HMO

try:
    hmo = HMO.objects.get(name__icontains='NHIS')
    print(f"HMO: {hmo.name} ({hmo.code})")
except HMO.DoesNotExist:
    print("ERROR: NHIS HMO not found."); exit()

# NHIS Medicines Price List October 2021 — Full extraction (all 47 pages)
# Format: (Name, Category, Price)
services = [
    # ── ANAESTHETICS ──────────────────────────────────────────────────
    ("Halothane Inhalation Liquid", "Pharmacy", 67),
    ("Ketamine Injection HCL", "Pharmacy", 1171),
    ("Nitrous Oxide Gas", "Pharmacy", 5000),
    ("Oxygen Per Hour", "Clinical Services", 500),
    ("Thiopental Injection IV", "Pharmacy", 3572),
    ("Atropine Injection 0.5mg", "Pharmacy", 59),
    ("Atropine Injection 1mg", "Pharmacy", 59),
    ("Diazepam Injection 5mg/2ml", "Pharmacy", 177),
    ("Hyoscine N-Butylbromide Injection 20mg", "Pharmacy", 65),
    ("Midazolam 15mg Injection", "Pharmacy", 2600),
    ("Morphine Injection 10mg SO4", "Pharmacy", 236),
    ("Morphine Injection 25mg HCL", "Pharmacy", 354),
    ("Promethazine Tablets 5mg", "Pharmacy", 6),
    ("Promethazine Syrup 25mg/ml", "Pharmacy", 200),
    ("Promethazine Injection 2ml", "Pharmacy", 30),
    ("Glycopyrollate 0.2mg Injection", "Pharmacy", 240),
    ("Atracurium Injection 50mg/ml", "Pharmacy", 2400),
    ("Edrophonium Injection Chloride 10mg", "Pharmacy", 1150),
    ("Neostigmine Injection Methylsulphate", "Pharmacy", 288),
    ("Pancuronium Injection Bromide 4mg", "Pharmacy", 632),
    ("Pancuronium Injection Bromide", "Pharmacy", 829),
    ("Suxamethonium Injection Chloride 100mg", "Pharmacy", 2548),
    ("Propofol 1% Injection", "Pharmacy", 2500),
    ("Lidocaine Injection HCL 1%/2%", "Pharmacy", 470),
    ("Bupivacaine Injection HCL", "Pharmacy", 590),
    ("Lidocaine 10%", "Pharmacy", 713),
    ("Lidocaine Topical Spray 2-4%", "Pharmacy", 1500),
    ("Lidocaine Jelly 2-5%", "Pharmacy", 900),
    ("Lidocaine Cream Ointment 2%", "Pharmacy", 850),
    ("Lidocaine Dental Cartridge", "Pharmacy", 570),
    ("Prilocaine Injection 3%", "Pharmacy", 800),
    # ── ANALGESICS NARCOTIC ────────────────────────────────────────────
    ("Morphine Injection 10mg/1ml Amp", "Pharmacy", 690),
    ("Morphine Injection 15mg/1ml Amp", "Pharmacy", 870),
    ("Morphine Tablet 30mg", "Pharmacy", 200),
    ("Pentazocine Injection Lactate 30mg", "Pharmacy", 200),
    ("Pethidine Injection 50mg/2ml", "Pharmacy", 250),
    ("Tramadol Tablet 50mg", "Pharmacy", 70),
    ("Tramadol Injection 50mg/ml", "Pharmacy", 373),
    ("Morphine Syrup 1mg/ml 200ml", "Pharmacy", 1000),
    ("Morphine Syrup 1mg/ml 500ml", "Pharmacy", 1500),
    ("Dihydrocodeine 30mg Tab", "Pharmacy", 30),
    ("Codeine Paracetamol 8/500mg Tab", "Pharmacy", 65),
    ("Codeine Paracetamol 30/500mg Tab", "Pharmacy", 100),
    ("Naloxone Injection 0.4mg/ml", "Pharmacy", 910),
    # ── NON-NARCOTIC ANALGESICS ────────────────────────────────────────
    ("Acetyl Salicylic Acid Tablet 300mg", "Pharmacy", 3),
    ("Paracetamol Tablets 500mg", "Pharmacy", 3),
    ("Paracetamol Suppository 100mg", "Pharmacy", 25),
    ("Paracetamol Syrup 125mg/5ml 60ml", "Pharmacy", 200),
    ("Paracetamol Drop 125mg/5ml 15ml", "Pharmacy", 250),
    ("Paracetamol Injection 150mg/ml", "Pharmacy", 30),
    # ── NSAIDs ────────────────────────────────────────────────────────
    ("Allopurinol Tablet 100mg", "Pharmacy", 31),
    ("Allopurinol Tablet 300mg", "Pharmacy", 55),
    ("Celecoxib Capsules 200mg", "Pharmacy", 240),
    ("Chondroitin Sulphate Glucosamine Caps", "Pharmacy", 60),
    ("Diclofenac Tablet 100mg", "Pharmacy", 30),
    ("Diclofenac Tablet 50mg", "Pharmacy", 20),
    ("Diclofenac Injection 25mg/ml", "Pharmacy", 50),
    ("Diclofenac Sodium Gel 1%", "Pharmacy", 500),
    ("Diclofenac Sodium Misoprostol Tab", "Pharmacy", 90),
    ("Diclofenac Sodium B1 B6 B12 Tab", "Pharmacy", 10),
    ("Diclofenac 100mg Suppository", "Pharmacy", 350),
    ("Diclofenac 50mg Suppository", "Pharmacy", 350),
    ("Ibuprofen Tablets 200mg", "Pharmacy", 15),
    ("Ibuprofen Tablets 400mg", "Pharmacy", 25),
    ("Ibuprofen Suspension 100mg/5ml", "Pharmacy", 250),
    ("Ketoprofen Capsules 200mg", "Pharmacy", 92),
    ("Ketoprofen Injection 100mg 2ml", "Pharmacy", 154),
    ("Naproxen Tablet 250mg", "Pharmacy", 25),
    ("Naproxen Tablet 500mg", "Pharmacy", 30),
    ("Piroxicam Capsules 20mg", "Pharmacy", 25),
    ("Piroxicam Injection 10mg/ml 2ml", "Pharmacy", 50),
    ("Meloxicam 15mg Capsule", "Pharmacy", 90),
    ("Meloxicam 7.5mg Capsule", "Pharmacy", 60),
    ("Tenoxicam Capsule 20mg", "Pharmacy", 100),
    ("Aceclofenac Tablet 100mg", "Pharmacy", 20),
    ("Aceclofenac Paracetamol Serratiopeptidase Tab", "Pharmacy", 150),
    ("Orphenadrine Tablet Citrate 100mg", "Pharmacy", 37),
    ("Orphenadrine Paracetamol Tablet", "Pharmacy", 43),
    ("Tizanidine Tablet 4mg", "Pharmacy", 65),
    ("Tizanidine Tablet 2mg", "Pharmacy", 65),
    ("Baclofen 10mg Tablet", "Pharmacy", 40),
    # ── ANTI-ALLERGICS ────────────────────────────────────────────────
    ("Cetrizine Tablet 10mg", "Pharmacy", 30),
    ("Cetrizine Syrup 1mg/5ml 100ml", "Pharmacy", 850),
    ("Chlorpheniramine Tablet 4mg", "Pharmacy", 5),
    ("Chlorpheniramine Syrup 2mg/5ml 60ml", "Pharmacy", 280),
    ("Chlorpheniramine Injection 10mg", "Pharmacy", 30),
    ("Clemastine Tablet 1mg", "Pharmacy", 46),
    ("Loratidine Tablet 10mg", "Pharmacy", 34),
    ("Loratidine Syrup 5mg/5ml 60ml", "Pharmacy", 620),
    ("Promethazine Tablets 25mg HCL", "Pharmacy", 3),
    ("Promethazine Syrup 5mg/5ml 60ml", "Pharmacy", 250),
    ("Promethazine Injection 25mg/ml", "Pharmacy", 40),
    ("Cinnarizine Tablet 25mg", "Pharmacy", 22),
    ("Fexofenadine 120mg Tablet", "Pharmacy", 90),
    ("Fexofenadine 180mg Tablet", "Pharmacy", 120),
    ("Dexamethasone Injection 4mg/1ml", "Pharmacy", 30),
    ("Epinephrine Adrenaline Injection 1mg/ml", "Pharmacy", 186),
    ("Hydrocortisone Injection 100mg Powder", "Pharmacy", 290),
    # ── ANTI-CONVULSANTS ──────────────────────────────────────────────
    ("Carbamazepine Tablet 200mg", "Pharmacy", 20),
    ("Carbamazepine Tablet 400mg SR", "Pharmacy", 30),
    ("Carbamazepine Syrup 100mg/5ml 100ml", "Pharmacy", 3855),
    ("Diazepam Injection 5mg/2ml NHIA", "Pharmacy", 300),
    ("Ethosuximide Caps 250mg", "Pharmacy", 140),
    ("Ethosuximide Syrup 250mg/5ml 100ml", "Pharmacy", 2181),
    ("Magnesium Sulphate Injection 50%", "Pharmacy", 290),
    ("Paraldehyde Injection 10ml", "Pharmacy", 327),
    ("Phenobarbital Tablets 15mg", "Pharmacy", 9),
    ("Phenobarbital Tablets 30mg 60mg", "Pharmacy", 13),
    ("Phenobarbital Elixir 15mg/5ml 60ml", "Pharmacy", 528),
    ("Phenobarbital Injection 200mg/ml", "Pharmacy", 300),
    ("Phenytoin Sodium Capsule 100mg", "Pharmacy", 38),
    ("Sodium Valproate Tablets 200mg", "Pharmacy", 39),
    ("Sodium Valproate Tablets 500mg SR", "Pharmacy", 90),
    ("Sodium Valproate Elixir 200mg/5ml 200ml", "Pharmacy", 2700),
    ("Pregabalin Tablet 75mg", "Pharmacy", 90),
    ("Pregabalin Tablet 150mg", "Pharmacy", 120),
    ("Pregabalin Methylcobalamin Tablet", "Pharmacy", 100),
    # ── ANTI-INFECTIVES - AMOEBICIDES ─────────────────────────────────
    ("Metronidazole Tablets 200mg", "Pharmacy", 6),
    ("Metronidazole Tablet 400mg", "Pharmacy", 10),
    ("Metronidazole Suspension 200mg/5ml 60ml", "Pharmacy", 230),
    ("Metronidazole IV Injection 500mg 100ml", "Pharmacy", 200),
    ("Metronidazole Suppository 500mg", "Pharmacy", 150),
    ("Secnidazole 4 Tablets 500mg", "Pharmacy", 500),
    ("Tinidazole 4 Tablets 500mg", "Pharmacy", 100),
    # ── ANTIHELMINTHICS ───────────────────────────────────────────────
    ("Albendazole Tablet 200mg 2 tabs", "Pharmacy", 100),
    ("Albendazole Suspension Oral 100mg/5ml", "Pharmacy", 100),
    ("Levamisole Tablet 40mg", "Pharmacy", 50),
    ("Levamisole Suspension 40mg/5ml 30ml", "Pharmacy", 150),
    ("Mebendazole Tablet 100mg 6s", "Pharmacy", 350),
    ("Mebendazole Tablet 500mg", "Pharmacy", 350),
    ("Mebendazole Suspension 100mg/5ml 30ml", "Pharmacy", 400),
    ("Pyrantel Pamoate Tablet 125mg 6s", "Pharmacy", 250),
    ("Pyrantel Pamoate Syrup 125mg/5ml 15ml", "Pharmacy", 400),
    ("Praziquantel Tablet 600mg", "Pharmacy", 60),
    ("Ivermectin Tablet 6mg", "Pharmacy", 5),
    # ── ANTI-MALARIALS ────────────────────────────────────────────────
    ("Artemether Injection Phosphate 80mg", "Pharmacy", 70),
    ("Artemether Injection Phosphate 40mg", "Pharmacy", 70),
    ("Artemether Lumefantrine Tablet 20/120mg 24s", "Pharmacy", 400),
    ("Artemether Lumefantrine Tablet 80/480mg 6s", "Pharmacy", 700),
    ("Artemether Lumefantrine Paediatric Dispersible", "Pharmacy", 30),
    ("Artemether Lumefantrine Suspension", "Pharmacy", 380),
    ("Artesunate Tablet 50mg 12 Tabs", "Pharmacy", 280),
    ("Artesunate 120mg Injection NHIA", "Pharmacy", 883),
    ("Artesunate 30mg Injection NHIA", "Pharmacy", 466),
    ("Artesunate 60mg Injection NHIA", "Pharmacy", 550),
    ("Artesunate Sulphadoxine Pyrimethamine Adult Tab", "Pharmacy", 800),
    ("Artesunate Amodiaquine Tablet 50/200mg 12s", "Pharmacy", 831),
    ("Artesunate Amodiaquine DS 200/600mg 6s", "Pharmacy", 850),
    ("Chloroquine Tablet Capsule 300mg", "Pharmacy", 20),
    ("Chloroquine Injection 200mg/5ml", "Pharmacy", 70),
    ("Chloroquine Syrup 75mg/5ml 60ml", "Pharmacy", 250),
    ("Dihydroartemisinin Piperaquine Tab 40/320mg 9s", "Pharmacy", 1000),
    ("Proguanil Tablet 100mg", "Pharmacy", 13),
    ("Pyrimethamine Sulphadoxine Tablet 3s", "Pharmacy", 200),
    ("Pyrimethamine Tablet 25mg", "Pharmacy", 30),
    ("Quinine Tablet 300mg", "Pharmacy", 50),
    ("Quinine Injection 300mg/2ml", "Pharmacy", 150),
    ("Quinine Syrup 100ml", "Pharmacy", 646),
    # ── ANTIBACTERIALS ────────────────────────────────────────────────
    ("Amikacin 500mg Injection", "Pharmacy", 700),
    ("Amoxycillin Capsule 250mg", "Pharmacy", 20),
    ("Amoxycillin Capsule 500mg", "Pharmacy", 30),
    ("Amoxycillin Suspension 125mg/5ml 100ml", "Pharmacy", 330),
    ("Amoxycillin Injection 500mg Vial", "Pharmacy", 200),
    ("Amoxycillin Clavulanic Acid 250mg Tab", "Pharmacy", 95),
    ("Amoxycillin Clavulanic Acid 500mg Tab", "Pharmacy", 100),
    ("Amoxicillin Clavulanic Acid 1g Tablet", "Pharmacy", 120),
    ("Amoxycillin Clavulanic Acid 200/28mg Suspension 100ml", "Pharmacy", 1150),
    ("Amoxycillin Clavulanic Acid 400/57mg Suspension 100ml", "Pharmacy", 1200),
    ("Amoxycillin Clavulanic Acid Injection 500mg Vial", "Pharmacy", 1000),
    ("Amoxycillin Clavulanic Acid Injection 1g Vial", "Pharmacy", 1200),
    ("Ampicillin Cloxacillin Capsule 250mg Each", "Pharmacy", 20),
    ("Ampicillin Cloxacillin Suspension 125mg/5ml 100ml", "Pharmacy", 300),
    ("Ampicillin Cloxacillin Neonatal Drops 8ml", "Pharmacy", 500),
    ("Ampicillin Cloxacillin Injection 250mg", "Pharmacy", 177),
    ("Ampicillin Sulbactam 1.5g Injection", "Pharmacy", 900),
    ("Ampicillin Sulbactam 3g Injection", "Pharmacy", 900),
    ("Azithromycin Capsules 250mg", "Pharmacy", 125),
    ("Azithromycin Capsules 500mg", "Pharmacy", 500),
    ("Azithromycin Suspension 200mg/5ml 30ml", "Pharmacy", 750),
    ("Benzathine Benzylpenicillin Injection 2.4MU", "Pharmacy", 614),
    ("Benzylpenicillin Injection 1.0MU Vial", "Pharmacy", 45),
    ("Benzylpenicillin Injection 5MU Vial", "Pharmacy", 65),
    ("Cefixime Tablet 400mg", "Pharmacy", 340),
    ("Cefixime Tablet 200mg", "Pharmacy", 180),
    ("Cefixime Suspension 100mg/5ml 100ml", "Pharmacy", 750),
    ("Cefotaxime Injection 500mg Vial", "Pharmacy", 400),
    ("Ceftazidime Injection 1g Vial", "Pharmacy", 700),
    ("Ceftriaxone Injection 250mg Vial", "Pharmacy", 500),
    ("Ceftriaxone Injection 500mg IM Vial", "Pharmacy", 500),
    ("Ceftriaxone Injection 1g IV Vial", "Pharmacy", 500),
    ("Cefuroxime Tablets 250mg", "Pharmacy", 150),
    ("Cefuroxime Tablets 500mg", "Pharmacy", 180),
    ("Cefuroxime Suspension 125mg/5ml 100ml", "Pharmacy", 1000),
    ("Cefuroxime Injection 750mg Vial", "Pharmacy", 450),
    ("Cefuroxime Injection 250mg Vial", "Pharmacy", 150),
    ("Cephalexin Capsule Tablet 500mg", "Pharmacy", 35),
    ("Cephalexin Suspension 125mg/5ml 100ml", "Pharmacy", 400),
    ("Cephalexin Suspension 250mg/5ml 100ml", "Pharmacy", 600),
    ("Chloramphenicol Capsule 250mg", "Pharmacy", 3),
    ("Chloramphenicol Suspension 125mg/5ml 100ml", "Pharmacy", 150),
    ("Chloramphenicol Injection 1g Vial", "Pharmacy", 200),
    ("Ciprofloxacin Tablet 250mg", "Pharmacy", 40),
    ("Ciprofloxacin Tablet 500mg", "Pharmacy", 40),
    ("Ciprofloxacin Infusion IV 2mg/ml 100ml", "Pharmacy", 200),
    ("Clarithromycin Tablet 250mg", "Pharmacy", 125),
    ("Clarithromycin Tablet 500mg", "Pharmacy", 180),
    ("Clarithromycin Suspension 125mg 100ml", "Pharmacy", 880),
    ("Clindamycin Capsule HCL 150mg", "Pharmacy", 75),
    ("Clindamycin Injection Phosphate 150mg", "Pharmacy", 600),
    ("Clindamycin Tablet 300mg", "Pharmacy", 80),
    ("Cloxacillin Injection 250mg Vial", "Pharmacy", 50),
    ("Cloxacillin Injection 500mg Vial", "Pharmacy", 70),
    ("Cloxacillin Capsule 250mg", "Pharmacy", 20),
    ("Cloxacillin Suspension 125mg/5ml 100ml", "Pharmacy", 200),
    ("Co-trimoxazole Tablet 400/80mg", "Pharmacy", 5),
    ("Co-trimoxazole Tablet 800/160mg DS", "Pharmacy", 10),
    ("Co-trimoxazole Suspension 200/40mg/5ml 60ml", "Pharmacy", 180),
    ("Doxycycline Capsule 100mg", "Pharmacy", 20),
    ("Erythromycin Tablet 250mg", "Pharmacy", 15),
    ("Erythromycin Tablet 500mg", "Pharmacy", 50),
    ("Erythromycin Suspension 125mg/5ml 60ml", "Pharmacy", 400),
    ("Ethambutol 400mg Tab", "Pharmacy", 50),
    ("Gentamycin Injection 80mg 40mg", "Pharmacy", 155),
    ("Imipenem Cilastin 500mg Injection", "Pharmacy", 2950),
    ("Isoniazid 300mg Tab", "Pharmacy", 60),
    ("Levofloxacin Tablet 250mg", "Pharmacy", 60),
    ("Levofloxacin Tablet 500mg", "Pharmacy", 70),
    ("Levofloxacin Tablet 750mg", "Pharmacy", 100),
    ("Levofloxacin Injection 500mg/100ml", "Pharmacy", 784),
    ("Lincomycin Capsules 500mg", "Pharmacy", 30),
    ("Lincomycin Suspension 250mg/5ml 100ml", "Pharmacy", 1150),
    ("Lincomycin Injection Phosphate 150mg", "Pharmacy", 150),
    ("Moxifloxacin Tablet 400mg", "Pharmacy", 210),
    ("Moxifloxacin Injection 400mg/250ml", "Pharmacy", 1500),
    ("Moxifloxacin Eye Drop 10ml", "Pharmacy", 600),
    ("Nitrofurantoin Tablet 50mg", "Pharmacy", 3),
    ("Nitrofurantoin 100mg Tab", "Pharmacy", 5),
    ("Ofloxacin Tablet 200mg", "Pharmacy", 50),
    ("Ofloxacin Infusion 200mg/100ml", "Pharmacy", 300),
    ("Pefloxacin Tablet 400mg", "Pharmacy", 100),
    ("Phenoxymethyl Penicillin Tablet 250mg", "Pharmacy", 15),
    ("Phenoxymethyl Penicillin Suspension 250mg/5ml", "Pharmacy", 200),
    ("Piperacillin Tazobactam 2.25g Vial", "Pharmacy", 1500),
    ("Pyrazinamide 500mg Tab", "Pharmacy", 50),
    ("Rifampicin Capsules 150mg 300mg", "Pharmacy", 20),
    ("Sparfloxacin Tablet 200mg", "Pharmacy", 70),
    ("Tetracycline Capsule 250mg", "Pharmacy", 20),
    ("Vancomycin Injection", "Pharmacy", 900),
    # ── ANTIFUNGALS ───────────────────────────────────────────────────
    ("Amphotericin B Injection 50mg Vial", "Pharmacy", 4996),
    ("Fluconazole Capsule 50mg", "Pharmacy", 60),
    ("Fluconazole Capsule 150mg", "Pharmacy", 60),
    ("Fluconazole Capsule 200mg", "Pharmacy", 225),
    ("Fluconazole Suspension 50mg/5ml 35ml", "Pharmacy", 1000),
    ("Fluconazole Injection IV 2mg/ml", "Pharmacy", 350),
    ("Griseofulvin Tablet 500mg", "Pharmacy", 17),
    ("Griseofulvin Suspension 125mg/5ml 100ml", "Pharmacy", 450),
    ("Itraconazole Capsules 100mg", "Pharmacy", 100),
    ("Itraconazole Suspension 10mg/ml", "Pharmacy", 340),
    ("Ketoconazole Tablet 200mg", "Pharmacy", 22),
    ("Nystatin Tablet 500000 units", "Pharmacy", 40),
    ("Nystatin Suspension 100000 units/ml 30ml", "Pharmacy", 380),
    ("Nystatin Pessary 100000 units", "Pharmacy", 37),
    ("Terbinafine Tablet 250mg", "Pharmacy", 170),
    # ── ANTIVIRALS ────────────────────────────────────────────────────
    ("Aciclovir Tablets 200mg", "Pharmacy", 153),
    ("Aciclovir Tablets 400mg", "Pharmacy", 268),
    ("Aciclovir Suspension 200mg/5ml 125ml", "Pharmacy", 800),
    ("Aciclovir Cream 5% Tube", "Pharmacy", 531),
    ("Aciclovir Injection IV 250mg Vial", "Pharmacy", 200),
    ("Lamivudine Tablet 150mg", "Pharmacy", 58),
    ("Sofosbuvir Tablet 400mg", "Pharmacy", 535),
    ("Ledipasvir Sofosbuvir Tablet 90/400mg", "Pharmacy", 3930),
    ("Daclatasvir Tablet 60mg", "Pharmacy", 357),
    ("Tenofovir 300mg Tablet", "Pharmacy", 108),
    # ── ARV FIXED DOSE COMBINATIONS ───────────────────────────────────
    ("Lamivudine Nevirapine Stavudine Tablet 150/200/30mg 60s", "Pharmacy", 1500),
    ("Lamivudine Nevirapine Zidovudine Tablet 30/50/60mg 60s", "Pharmacy", 2600),
    ("Lamivudine Zidovudine Tablet 150/300mg", "Pharmacy", 4500),
    ("Nevirapine Syrup 50mg/5ml", "Pharmacy", 4500),
    ("Ribavirin 200mg Tablet", "Pharmacy", 500),
    # ── ANTI-MIGRAINE ─────────────────────────────────────────────────
    ("Ergotamine Tablet Tartrate 2g", "Pharmacy", 59),
    ("Ergotamine Tartrate Caffeine Tablet 1/100mg", "Pharmacy", 70),
    ("Pizotifen Tablets 0.5mg 1.5mg", "Pharmacy", 42),
    ("Pizotifen Elixir 0.25mg/ml 100ml", "Pharmacy", 2360),
    ("Propranolol Tablet 40mg", "Pharmacy", 11),
    # ── IMMUNOSUPPRESSIVES ────────────────────────────────────────────
    ("Azathioprine Tablet 50mg", "Pharmacy", 120),
    ("Dexamethasone Tablet 0.5mg", "Pharmacy", 10),
    ("Dexamethasone Injection 4mg/ml Amp", "Pharmacy", 30),
    ("Methotrexate Tablet 2.5mg", "Pharmacy", 50),
    ("Methotrexate Injection 50mg Vial", "Pharmacy", 590),
    ("Prednisolone Tablet 5mg", "Pharmacy", 10),
    # ── ANTI-PARKINSONISM ─────────────────────────────────────────────
    ("Benzhexol Tablets 2mg", "Pharmacy", 6),
    ("Benzhexol Tablets 5mg HCL", "Pharmacy", 6),
    ("Biperiden Tablet 2mg HCL", "Pharmacy", 4),
    ("Biperiden Injection 5mg/ml", "Pharmacy", 47),
    ("Levodopa Carbidopa Tablet 250/25mg", "Pharmacy", 94),
    ("Levodopa Carbidopa Tablet 100/10mg", "Pharmacy", 83),
    ("Neostigmine Tablet 15mg Bromide", "Pharmacy", 165),
    ("Pyridostigmine Tablet 60mg Bromide", "Pharmacy", 177),
    # ── ANTISEPTICS AND DISINFECTANTS ─────────────────────────────────
    ("Chlorhexidine Solution 5% 500ml", "Pharmacy", 590),
    ("Chlorhexidine Cetrimide Solution 500ml", "Pharmacy", 472),
    ("Chloroxylenol Solution 5% 250ml", "Pharmacy", 472),
    ("Iodine Solution 1% 30ml", "Pharmacy", 118),
    ("Methylated Spirit 200ml", "Pharmacy", 118),
    ("Povidone Iodine Solution 10%", "Pharmacy", 236),
    ("Sodium Hypochlorite Solution 500ml", "Pharmacy", 177),
    ("Hydrogen Peroxide 6% Bottle", "Pharmacy", 200),
    # ── BLOOD DRUGS ───────────────────────────────────────────────────
    ("Cyanocobalamin Hydroxocobalamin Tablet 0.05mg", "Pharmacy", 6),
    ("Cyanocobalamin Hydroxocobalamin Injection", "Pharmacy", 110),
    ("Ferrous Sulphate Tablets 200mg", "Pharmacy", 4),
    ("Folic Acid Tablet 5mg", "Pharmacy", 4),
    ("Iron Dextran Injection 50mg/ml 2ml", "Pharmacy", 236),
    ("Enoxaparin Injection 40mg Syringe", "Pharmacy", 1416),
    ("Enoxaparin Injection 20mg Syringe", "Pharmacy", 1003),
    ("Heparin Sodium Injection 5000 units", "Pharmacy", 732),
    ("Heparin Sodium Injection 25000 units", "Pharmacy", 1416),
    ("Warfarin Sodium Tablets 3mg", "Pharmacy", 35),
    ("Warfarin Sodium Tablets 5mg", "Pharmacy", 35),
    ("Dabigatran 110mg Tab", "Pharmacy", 850),
    ("Acetylsalicylic Acid Tablet 75mg", "Pharmacy", 3),
    ("Dipyridamole Tablet 25mg", "Pharmacy", 72),
    ("Aminocaproic Acid Tablet 500mg", "Pharmacy", 3),
    ("Tranexamic Acid 500mg Injection", "Pharmacy", 285),
    ("Dextran 70 Injection IV 500ml", "Pharmacy", 1200),
    # ── CARDIOVASCULAR - ANTI-ANGINAL ─────────────────────────────────
    ("Atenolol Tablet 25mg", "Pharmacy", 16),
    ("Atenolol Tablet 50mg", "Pharmacy", 18),
    ("Atenolol Tablet 100mg", "Pharmacy", 30),
    ("Atenolol Injection 0.5mg/ml", "Pharmacy", 82),
    ("Glyceryl Trinitrate Tablet Sublingual 0.5mg", "Pharmacy", 100),
    ("Isosorbide Dinitrate Tablet 5mg", "Pharmacy", 25),
    ("Isosorbide Dinitrate Tablet 10mg", "Pharmacy", 40),
    ("Propranolol Tablet 40mg NHIA", "Pharmacy", 40),
    ("Propranolol Injection 1mg/ml NHIA", "Pharmacy", 200),
    ("Bisoprolol 2.5mg Tablet", "Pharmacy", 30),
    ("Bisoprolol 5mg Tablet", "Pharmacy", 30),
    ("Isosorbide Mononitrate 60mg Tab", "Pharmacy", 250),
    ("Trimetazidine 35mg Tab", "Pharmacy", 83),
    # ── ANTI-ARRHYTHMIC ───────────────────────────────────────────────
    ("Amiodarone Tab 200mg", "Pharmacy", 54),
    ("Lidocaine Injection 20mg/ml 5ml", "Pharmacy", 713),
    ("Procainamide Tab 250mg HCL", "Pharmacy", 146),
    ("Disopyramide Tab 100mg 150mg", "Pharmacy", 86),
    ("Procainamide Injection 100mg 10ml", "Pharmacy", 250),
    # ── DIURETICS ─────────────────────────────────────────────────────
    ("Amiloride Hydrochlorothiazide Tablet 5/50mg", "Pharmacy", 20),
    ("Bendrofluazide Tablet 5mg", "Pharmacy", 15),
    ("Frusemide Tablet 40mg", "Pharmacy", 8),
    ("Frusemide Injection 10mg/ml 2ml", "Pharmacy", 50),
    ("Hydrochlorothiazide Tablet 25mg", "Pharmacy", 6),
    ("Hydrochlorothiazide Tablet 50mg", "Pharmacy", 6),
    ("Spironolactone Tablet 25mg", "Pharmacy", 5),
    ("Spironolactone Tablet 50mg", "Pharmacy", 27),
    ("Spironolactone Tablet 100mg", "Pharmacy", 86),
    ("Torsemide Tablet 100mg", "Pharmacy", 83),
    ("Torsemide Tablet 10mg", "Pharmacy", 23),
    ("Torsemide Tablet 20mg", "Pharmacy", 50),
    ("Torsemide Injection 10mg/ml", "Pharmacy", 500),
    ("Torsemide Injection 20mg", "Pharmacy", 900),
    # ── ANTIHYPERTENSIVES ─────────────────────────────────────────────
    ("Amlodipine Tablet 5mg", "Pharmacy", 20),
    ("Amlodipine Tablet 10mg", "Pharmacy", 22),
    ("Captopril Tablet 12.5mg", "Pharmacy", 15),
    ("Captopril Tablet 25mg", "Pharmacy", 20),
    ("Captopril Tablet 50mg", "Pharmacy", 57),
    ("Carvedilol 12.5mg Tab", "Pharmacy", 26),
    ("Carvedilol 25mg Tablet", "Pharmacy", 54),
    ("Carvedilol 6.25mg Tab", "Pharmacy", 30),
    ("Enalapril Tablet 5mg", "Pharmacy", 30),
    ("Enalapril Tablet 10mg", "Pharmacy", 35),
    ("Hydralazine Tablet 25mg", "Pharmacy", 15),
    ("Hydralazine Tablet 50mg", "Pharmacy", 25),
    ("Hydralazine Injection 20mg Amp", "Pharmacy", 170),
    ("Indapamide 1.5mg Tab", "Pharmacy", 117),
    ("Irbesartan Tablet 300mg", "Pharmacy", 143),
    ("Irbesartan 150mg Tablet", "Pharmacy", 171),
    ("Labetalol Tablet HCL 200mg", "Pharmacy", 82),
    ("Labetalol Injection 5mg/ml 20ml", "Pharmacy", 200),
    ("Lisinopril Tablet 2.5mg", "Pharmacy", 20),
    ("Lisinopril Tablet 5mg", "Pharmacy", 25),
    ("Lisinopril Tablet 10mg", "Pharmacy", 32),
    ("Lisinopril Hydrochlorothiazide Tablet 20/12.5mg", "Pharmacy", 55),
    ("Losartan 25mg Tablet", "Pharmacy", 60),
    ("Losartan 50mg Tablet", "Pharmacy", 60),
    ("Losartan Amlodipine Tablet 50/5mg", "Pharmacy", 122),
    ("Methyldopa Tablet 500mg", "Pharmacy", 50),
    ("Metoprolol 25mg Tablet", "Pharmacy", 121),
    ("Metoprolol 50mg Tablet", "Pharmacy", 73),
    ("Metoprolol Succinate 100mg Tab", "Pharmacy", 97),
    ("Nebivolol Tablet 5mg", "Pharmacy", 70),
    ("Nifedipine Tablet 20mg", "Pharmacy", 33),
    ("Nifedipine Slow Release 30mg", "Pharmacy", 50),
    ("Olmesartan Tablet 20mg 40mg", "Pharmacy", 180),
    ("Perindopril Tablet 5mg", "Pharmacy", 175),
    ("Perindopril Tablet 10mg", "Pharmacy", 233),
    ("Prazosin Tablet 1mg", "Pharmacy", 20),
    ("Prazosin Tablet 2mg", "Pharmacy", 25),
    ("Ramipril 10mg Tablet", "Pharmacy", 22),
    ("Ramipril 5mg Tablet", "Pharmacy", 50),
    ("S-Amlodipine 5mg Tablet", "Pharmacy", 88),
    ("Telmisartan Tablet 40mg", "Pharmacy", 80),
    ("Telmisartan Tablet 80mg", "Pharmacy", 90),
    ("Telmisartan Hydrochlorothiazide 40/12.5mg", "Pharmacy", 95),
    ("Valsartan Tab 80mg", "Pharmacy", 95),
    ("Valsartan Tab 160mg", "Pharmacy", 83),
    # ── CARDIAC GLYCOSIDES ────────────────────────────────────────────
    ("Digoxin Tablets 0.25mg", "Pharmacy", 31),
    ("Digoxin Injection 0.25mg/ml 2ml", "Pharmacy", 300),
    ("Digoxin Syrup 50mg/ml 100ml", "Pharmacy", 500),
    ("Dopamine Injection 40mg/ml 5ml", "Pharmacy", 400),
    ("Dobutamine 250mg/20ml Injection", "Pharmacy", 430),
    # ── LIPID REGULATING ──────────────────────────────────────────────
    ("Atorvastatin Tablet 10mg", "Pharmacy", 54),
    ("Atorvastatin Tablet 20mg", "Pharmacy", 80),
    ("Atorvastatin 40mg Tablet", "Pharmacy", 200),
    ("Fluvastatin Tab 40mg", "Pharmacy", 50),
    ("Rosuvastatin Tab 5mg", "Pharmacy", 182),
    ("Rosuvastatin Tab 10mg", "Pharmacy", 110),
    ("Rosuvastatin Tab 20mg", "Pharmacy", 117),
    ("Simvastatin Tab 10mg", "Pharmacy", 21),
    ("Simvastatin Tab 20mg", "Pharmacy", 38),
    ("Simvastatin Tab 40mg", "Pharmacy", 38),
    # ── DENTAL ────────────────────────────────────────────────────────
    ("Benzocaine Lozenges 10mg", "Pharmacy", 162),
    ("Lidocaine Dental Injection 2%", "Pharmacy", 470),
    ("Lidocaine Spray Tin", "Pharmacy", 1500),
    ("Nystatin Solution 100000 unit/ml 30ml", "Pharmacy", 736),
    # ── DERMATOLOGICAL ────────────────────────────────────────────────
    ("Acyclovir Cream 5% Derma", "Pharmacy", 531),
    ("Gentamicin Ointment 0.30% Tube", "Pharmacy", 177),
    ("Gentian Violet Aqueous Solution 0.50% 60ml", "Pharmacy", 94),
    ("Mupirocin Ointment 2% Tube", "Pharmacy", 1180),
    ("Silver Sulphadiazine Cream 1% Tube", "Pharmacy", 472),
    ("Betamethasone Cream 0.1% Tube", "Pharmacy", 295),
    ("Betamethasone Neomycin Cream Tube", "Pharmacy", 354),
    ("Clobetasol Propionate Cream 0.05% Tube", "Pharmacy", 1003),
    ("Hydrocortisone Cream 1% Tube", "Pharmacy", 354),
    ("Methyl Salicylate Ointment Tube", "Pharmacy", 295),
    ("Clotrimazole Cream 1% Tube", "Pharmacy", 236),
    ("Clotrimazole Pessary 6s", "Pharmacy", 413),
    ("Clotrimazole Vaginal Cream Tube", "Pharmacy", 590),
    ("Ketoconazole Cream 2% Tube", "Pharmacy", 649),
    ("Miconazole Cream 2% Tube", "Pharmacy", 472),
    ("Miconazole Ovule", "Pharmacy", 826),
    ("Nystatin Cream Oint 100000 units Tube", "Pharmacy", 590),
    ("Terbinafine 1% Cream", "Pharmacy", 2340),
    ("Benzoic Acid Salicylic Acid Cream 6/3%", "Pharmacy", 236),
    ("Benzyl Benzoate Emulsion 25% 100ml", "Pharmacy", 260),
    ("Permethrin Cream Lotion", "Pharmacy", 118),
    ("Calamine Lotion 120ml", "Pharmacy", 236),
    ("Benzoyl Peroxide Cream 10%", "Pharmacy", 1062),
    # ── EAR NOSE THROAT ───────────────────────────────────────────────
    ("Chloramphenicol Ear Drops 5% 10ml", "Pharmacy", 177),
    ("Gentamicin Eye Ear Drops 0.3% 10ml", "Pharmacy", 177),
    ("Betamethasone Neomycin Ear Drops 10ml", "Pharmacy", 295),
    ("Hydrocortisone Neomycin Ear Drops 5ml", "Pharmacy", 420),
    ("Beclomethasone Dipropionate Nasal Spray", "Pharmacy", 1770),
    ("Pseudoephedrine HCL Tablet 60mg", "Pharmacy", 6),
    ("Pseudoephedrine HCL Syrup 30mg/5ml 60ml", "Pharmacy", 354),
    ("Xylometazoline Nasal Drops 0.50% 10ml", "Pharmacy", 885),
    ("Dequalinium Lozenges 250mg", "Pharmacy", 12),
    # ── GASTROINTESTINAL ──────────────────────────────────────────────
    ("Aluminium Hydroxide Suspension 320mg/5ml 200ml", "Pharmacy", 236),
    ("Aluminium Hydroxide Tablet 500mg", "Pharmacy", 6),
    ("Aluminium Hydroxide Magnesium Hydroxide Simethicone Tab", "Pharmacy", 6),
    ("Magnesium Trisilicate Tablet 500mg", "Pharmacy", 6),
    ("Magnesium Trisilicate Mixture 250mg/ml 200ml", "Pharmacy", 354),
    ("Metoclopramide Tablet 10mg HCL", "Pharmacy", 8),
    ("Metoclopramide Syrup 5mg/5ml 100ml", "Pharmacy", 236),
    ("Metoclopramide Injection 5mg/ml", "Pharmacy", 35),
    ("Prochlorperazine Tablet 5mg", "Pharmacy", 6),
    ("Prochlorperazine Injection 12.5mg/ml", "Pharmacy", 83),
    ("Promethazine Tablet 10mg 25mg", "Pharmacy", 6),
    ("Promethazine Injection 25mg/ml 2ml", "Pharmacy", 24),
    ("Hyoscine N-Butylbromide Tablet 10mg NHIA", "Pharmacy", 12),
    ("Hyoscine N-Butylbromide Injection 20mg/ml", "Pharmacy", 59),
    ("Bisacodyl Tablet 5mg", "Pharmacy", 6),
    ("Bisacodyl Suppositories 5mg 10mg", "Pharmacy", 153),
    ("Liquid Paraffin Emulsion 100ml", "Pharmacy", 260),
    ("Senna Tablet Granule", "Pharmacy", 35),
    ("Lactulose Syrup 120ml", "Pharmacy", 1900),
    ("Loperamide Tablet 2mg", "Pharmacy", 19),
    ("Oral Rehydration Salt Sachet", "Pharmacy", 50),
    ("Domperidone 10mg Tab", "Pharmacy", 150),
    ("Cimetidine Tablets 200mg", "Pharmacy", 12),
    ("Cimetidine Tablets 400mg", "Pharmacy", 18),
    ("Cimetidine Injection 100mg/ml 2ml", "Pharmacy", 118),
    ("Esomeprazole Tablet 20mg", "Pharmacy", 41),
    ("Esomeprazole 40mg Tablet NHIA", "Pharmacy", 600),
    ("Lansoprazole Capsule 30mg", "Pharmacy", 47),
    ("Omeprazole Tablet 20mg", "Pharmacy", 39),
    ("Rabeprazole Tablet 20mg", "Pharmacy", 83),
    ("Ranitidine Tablets 150mg", "Pharmacy", 19),
    ("Ranitidine Tablets 300mg HCL", "Pharmacy", 35),
    ("Ranitidine Injection 25mg/ml 2ml", "Pharmacy", 260),
    # ── HORMONES - CORTICOSTEROIDS ────────────────────────────────────
    ("Dexamethasone Tablets 0.5mg", "Pharmacy", 10),
    ("Dexamethasone Injection 4mg/ml 2ml Amp", "Pharmacy", 24),
    ("Fludrocortisone Tablet 0.1mg", "Pharmacy", 6),
    ("Hydrocortisone Injection Powder 100mg Vial", "Pharmacy", 177),
    ("Methyl Prednisolone Injection 40mg/ml 2ml", "Pharmacy", 1416),
    ("Prednisolone Tablets 1mg 5mg", "Pharmacy", 6),
    ("Triamcinolone Injection 10mg/40mg/ml", "Pharmacy", 1180),
    # ── ANTIDIABETICS INJECTABLE ──────────────────────────────────────
    ("Biphasic Isophane Insulin Injection Vial", "Pharmacy", 4620),
    ("Insulin Soluble Injection 100 units/ml Vial", "Pharmacy", 4805),
    ("Insulin Zinc Suspension 100 units/ml Vial", "Pharmacy", 4881),
    ("Isophane Insulin Injection 100 units/ml Vial", "Pharmacy", 4878),
    ("Insulin Glargine Lantus Cartridge 100iu/ml 3ml", "Pharmacy", 2019),
    # ── ANTIDIABETICS ORAL ────────────────────────────────────────────
    ("Chlorpropamide Tablets 250mg", "Pharmacy", 25),
    ("Metformin Tablets 500mg", "Pharmacy", 14),
    ("Metformin Tablets 850mg", "Pharmacy", 53),
    ("Metformin Tablets 1000mg", "Pharmacy", 18),
    ("Glibenclamide Tablets 5mg", "Pharmacy", 15),
    ("Gliclazide Tablet 80mg", "Pharmacy", 15),
    ("Gliclazide Tablet 30mg", "Pharmacy", 53),
    ("Glimepiride Tab 1mg", "Pharmacy", 30),
    ("Glimepiride Tab 2mg", "Pharmacy", 38),
    ("Glimepiride Tab 4mg", "Pharmacy", 67),
    ("Metformin Glibenclamide Tablet 500/2.5mg", "Pharmacy", 83),
    ("Pioglitazone Hydrochloride Tab 15mg", "Pharmacy", 122),
    ("Pioglitazone Hydrochloride Tab 30mg", "Pharmacy", 51),
    # ── THYROID ───────────────────────────────────────────────────────
    ("Carbimazole Tablets 5mg", "Pharmacy", 19),
    ("Levothyroxine Tablets 0.05mg", "Pharmacy", 59),
    ("Levothyroxine Tablets 0.1mg", "Pharmacy", 59),
    ("Propylthiouracil Tablet 50mg", "Pharmacy", 225),
    # ── PROSTATIC ─────────────────────────────────────────────────────
    ("Dutasteride Tablet", "Pharmacy", 160),
    ("Finasteride Tablet 5mg", "Pharmacy", 79),
    ("Tamsulosin Tablet 400mcg", "Pharmacy", 67),
    ("Alfuzosin 10mg Tablet", "Pharmacy", 155),
    # ── IMMUNOLOGICALS / VACCINES ─────────────────────────────────────
    ("Hepatitis B Vaccine Injection", "Clinical Services", 2550),
    ("Measles Mumps Rubella Vaccine 0.5ml", "Clinical Services", 2850),
    ("Tetanus Vaccine 0.5ml NHIA", "Clinical Services", 150),
    ("Cholera Vaccine Injection", "Clinical Services", 2350),
    ("HPV Vaccine Quadrivalent 0.5ml", "Clinical Services", 9600),
    ("Meningococcal Vaccine", "Clinical Services", 6450),
    ("Pneumococcal Vaccine 55mcg/0.5ml", "Clinical Services", 8200),
    ("Rabies Vaccine 1ml", "Clinical Services", 4651),
    ("Typhoid Vaccine TAB 1.5ml/vial", "Clinical Services", 450),
    # ── OPHTHALMOLOGICAL ──────────────────────────────────────────────
    ("Chloramphenicol Eye Ointment 1% 5gm", "Pharmacy", 200),
    ("Chloramphenicol Eye Drops 0.50% 10ml", "Pharmacy", 250),
    ("Ciprofloxacin Drops 0.30% 10ml", "Pharmacy", 800),
    ("Gentamicin Eye Drops 0.3% 10ml", "Pharmacy", 200),
    ("Natamycin Eye Drops 50mg/ml 5ml", "Pharmacy", 700),
    ("Ofloxacin Eye Drops 0.30% 10ml", "Pharmacy", 500),
    ("Levofloxacin 0.5% Eyedrop", "Pharmacy", 500),
    ("Betamethasone Eye Drops 0.10% 10ml", "Pharmacy", 500),
    ("Dexamethasone Eye Drops 0.10% 10ml", "Pharmacy", 1000),
    ("Prednisolone Eye Drops 1% 5ml", "Pharmacy", 500),
    ("Sodium Cromoglycate 2% Eyedrop", "Pharmacy", 1200),
    ("Acetazolamide Tablet 250mg", "Pharmacy", 13),
    ("Pilocarpine Eye Drops 2% 4% 5ml", "Pharmacy", 480),
    ("Timolol Eye Drops 0.25 0.5% 10ml", "Pharmacy", 500),
    ("Atropine Eye Drops 0.5% 1% 5ml", "Pharmacy", 490),
    ("Tropicamide Eye Drops 0.5% 1% 10ml", "Pharmacy", 850),
    # ── OXYTOCICS ─────────────────────────────────────────────────────
    ("Ergometrine Tablet 0.5mg Maleate", "Pharmacy", 10),
    ("Ergometrine Injection 0.5mg/ml Maleate", "Pharmacy", 400),
    ("Oxytocin Injection 10 units/ml", "Pharmacy", 400),
    ("Dinoprostone Pessary 3mg", "Pharmacy", 200),
    ("Misoprostol Tablet 200mcg", "Pharmacy", 125),
    # ── ELECTROLYTES ──────────────────────────────────────────────────
    ("Darrow Solution IVF 500ml", "Pharmacy", 400),
    ("Dextrose Sodium Chloride IVF 5%/0.9% 500ml", "Pharmacy", 400),
    ("Glucose Dextrose Injection 5% 10% 500ml", "Pharmacy", 400),
    ("Glucose Dextrose Injection 50% 500ml", "Pharmacy", 400),
    ("Glucose Sodium Chloride Paediatric IVF 500ml", "Pharmacy", 400),
    ("Mannitol Infusion 10% NHIA", "Pharmacy", 400),
    ("Mannitol Infusion 20% NHIA", "Pharmacy", 400),
    ("Potassium Chloride Injection 15% 10ml", "Pharmacy", 400),
    ("Ringers Lactate Solution 100ml", "Pharmacy", 400),
    ("Sodium Lactate Compound Solution IVF 500ml", "Pharmacy", 400),
    ("Sodium Bicarbonate Injection 1.4% 10ml", "Pharmacy", 400),
    ("Normal Saline 0.9% 0.45% Infusion", "Pharmacy", 400),
    # ── PSYCHOTHERAPEUTIC ─────────────────────────────────────────────
    ("Bromazepam Tablet 1.5mg", "Pharmacy", 23),
    ("Bromazepam Tablet 3mg", "Pharmacy", 40),
    ("Diazepam Tablets 5mg 2mg 10mg", "Pharmacy", 45),
    ("Diazepam Injection 5mg/ml 2ml NHIA", "Pharmacy", 430),
    ("Lorazepam Tablets 1mg", "Pharmacy", 10),
    ("Lorazepam Tablets 2mg", "Pharmacy", 10),
    ("Nitrazepam Tablets 5mg", "Pharmacy", 53),
    ("Clonazepam 2mg Tablet", "Pharmacy", 33),
    ("Amitriptyline Tablets 25mg HCL", "Pharmacy", 9),
    ("Amitriptyline Tablet 50mg", "Pharmacy", 18),
    ("Clomipramine Tablet 10mg", "Pharmacy", 66),
    ("Imipramine Tablets 10mg", "Pharmacy", 5),
    ("Imipramine Tablet 25mg HCL", "Pharmacy", 5),
    ("Paroxetine Tablet 20mg", "Pharmacy", 86),
    ("Sertraline Capsule 50mg", "Pharmacy", 42),
    ("Fluoxetine Tablet 20mg", "Pharmacy", 67),
    ("Escitalopram 10mg Tablet", "Pharmacy", 30),
    ("Olanzapine Tablet 5mg 10mg", "Pharmacy", 86),
    ("Chlorpromazine Tablets 25mg", "Pharmacy", 10),
    ("Chlorpromazine Tablet 50mg", "Pharmacy", 10),
    ("Chlorpromazine Tablet 100mg HCL", "Pharmacy", 10),
    ("Chlorpromazine Injection 25mg/ml 2ml Amp", "Pharmacy", 118),
    ("Flupenthixol Tablet 1.5mg 3mg", "Pharmacy", 10),
    ("Haloperidol Tablet 2mg", "Pharmacy", 20),
    ("Haloperidol Injection 5mg/ml", "Pharmacy", 150),
    ("Thioridazine Tablet 100mg", "Pharmacy", 150),
    ("Trifluoperazine Tablet 1mg", "Pharmacy", 10),
    ("Trifluoperazine Tablet 5mg", "Pharmacy", 15),
    ("Valproic Acid Sodium Valproate Tab 200mg", "Pharmacy", 100),
    ("Valproic Acid Sodium Valproate Tab 500mg", "Pharmacy", 150),
    ("Benzhexol Trihexyphenidyl Tablets 2mg 5mg", "Pharmacy", 10),
    ("Risperidone 0.5mg Tablet", "Pharmacy", 26),
    ("Risperidone 1mg Tablet", "Pharmacy", 40),
    ("Risperidone 2mg Tablet", "Pharmacy", 65),
    # ── RESPIRATORY ───────────────────────────────────────────────────
    ("Aminophylline Injection 25mg/ml 10ml", "Pharmacy", 100),
    ("Beclomethasone Aerosol Inhalation 0.05mg", "Pharmacy", 2300),
    ("Epinephrine Adrenaline Injection 1mg/ml 1ml", "Pharmacy", 50),
    ("Ipratropium Bromide Inhalation Aerosol", "Pharmacy", 375),
    ("Salbutamol Tablets 2mg 4mg", "Pharmacy", 10),
    ("Salbutamol Syrup 2mg/5ml 100ml", "Pharmacy", 400),
    ("Salbutamol Aerosol 0.1mg/metered dose", "Pharmacy", 1700),
    ("Salbutamol 2.5mg Nebule", "Pharmacy", 230),
    ("Salbutamol 5mg Nebule", "Pharmacy", 400),
    ("Salbutamol Injection 500ug/ml", "Pharmacy", 450),
    ("Salmeterol Inhalation 100mcg/dose", "Pharmacy", 2300),
    ("Salmeterol Fluticasone Inhalation 250/100mcg", "Pharmacy", 2300),
    ("Theophylline Tablet 125mg", "Pharmacy", 20),
    ("Theophylline Tablet 250mg SR", "Pharmacy", 40),
    ("Budesonide 0.5 Nebule", "Pharmacy", 500),
    ("Montelukast Tablet 10mg", "Pharmacy", 118),
    ("Montelukast Tablet 5mg", "Pharmacy", 108),
    ("Montelukast Tablet 4mg", "Pharmacy", 100),
    ("Bromhexine Tablet 8mg", "Pharmacy", 35),
    ("Bromhexine Elixir 4mg/5ml 100ml", "Pharmacy", 200),
    # ── VITAMINS ──────────────────────────────────────────────────────
    ("Alpha Tocopherol Vitamin E Capsule 400IU", "Pharmacy", 50),
    ("Ascorbic Acid Tablets 100mg", "Pharmacy", 3),
    ("Cyanocobalamin B12 Injection 0.25mg", "Pharmacy", 150),
    ("Cyanocobalamin B12 Tablet 0.05mg", "Pharmacy", 5),
    ("Ergocalciferol Vitamin D Tablets 0.25mg", "Pharmacy", 10),
    ("Folic Acid Tablet 5mg NHIA", "Pharmacy", 3),
    ("Multivitamin Syrup 100ml", "Pharmacy", 200),
    ("Multivitamin Tablet", "Pharmacy", 5),
    ("Multivitamin Drops 10ml", "Pharmacy", 300),
    ("Pyridoxine Vitamin B6 Tablets 10mg", "Pharmacy", 5),
    ("Retinol Vitamin A Tablets 1.5mg", "Pharmacy", 20),
    ("Riboflavin Vitamin B2 Tablets 5mg", "Pharmacy", 5),
    ("Thiamine Vitamin B1 Tablets 25mg 50mg", "Pharmacy", 5),
    ("Vitamin B Complex Tablets", "Pharmacy", 5),
    ("Vitamin B Complex Syrup 100ml", "Pharmacy", 200),
    ("Vitamin B Complex Injection Vial", "Pharmacy", 200),
    ("Vitamins B1 B6 B12 Tablet 100/200/200mcg", "Pharmacy", 80),
    ("Vitamins B1 B6 B12 Injection 100/100/1000mcg", "Pharmacy", 200),
    # ── MINERALS ──────────────────────────────────────────────────────
    ("Calcium Gluconate Tablets 600mg", "Pharmacy", 5),
    ("Calcium Lactate Tablets 300mg", "Pharmacy", 5),
    ("Calcium Carbonate 600mg Vitamin D3 Tab", "Pharmacy", 60),
    ("Calcium Gluconate 10% Injection", "Pharmacy", 90),
    ("Zinc 20mg Dispersible Tablet", "Pharmacy", 10),
    ("Zinc Sulphate Tablet 20mg", "Pharmacy", 12),
    # ── CYTOTOXICS ────────────────────────────────────────────────────
    ("5-Fluorouracil Injection 500mg", "Pharmacy", 550),
    ("Anastrozole Tablet 1mg", "Pharmacy", 302),
    ("Hydroxyurea Tablet 200-500mg", "Pharmacy", 70),
    ("Ondansetron Injection 8mg Vial", "Pharmacy", 850),
    ("Ondansetron Tablet 4mg", "Pharmacy", 46),
    ("Tamoxifen Tablet 20mg", "Pharmacy", 67),
    # ── CONSUMABLES ───────────────────────────────────────────────────
    ("Blood Giving Set NHIA", "Consumables", 300),
    ("Chromic Catgut All Sizes", "Consumables", 600),
    ("Cotton Wool Roll", "Consumables", 150),
    ("Crepe Bandage Roll", "Consumables", 400),
    ("Foley Catheter NHIA", "Consumables", 600),
    ("Infusion Set NHIA", "Consumables", 150),
    ("IV Cannula NHIA 14G-25G", "Consumables", 150),
    ("Mucus Extractor All Sizes", "Consumables", 250),
    ("Needle NHIA", "Consumables", 50),
    ("NG Tube NHIA", "Consumables", 170),
    ("Nylon Suture All Sizes", "Consumables", 309),
    ("Plaster Roll All Sizes", "Consumables", 400),
    ("Scalp Vein Needle NHIA", "Consumables", 50),
    ("Surgical Blade All Sizes", "Consumables", 50),
    ("Surgical Gloves NHIA", "Consumables", 100),
    ("Syringe 2ml NHIA", "Consumables", 50),
    ("Syringe 5ml NHIA", "Consumables", 50),
    ("Syringe 10ml NHIA", "Consumables", 50),
    ("Syringe 20ml NHIA", "Consumables", 70),
    ("Urine Bag NHIA", "Consumables", 300),
    ("Insulin Needles NHIA", "Consumables", 150),
    # ── CLINICAL SERVICES (NHIA covered) ──────────────────────────────
    ("Echocardiography NHIA", "Clinical Services", 12000),
    ("ECG NHIA", "Clinical Services", 5000),
    ("Delivery NHIA", "Clinical Services", 12000),
    ("Anti Natal NHIA", "Clinical Services", 15000),
    ("Abdomino Pelvic Scan NHIA", "Clinical Services", 4000),
    ("Pelvic Scan NHIA", "Clinical Services", 3000),
    ("Obstetric Scan NHIA", "Clinical Services", 3000),
    ("Wound Dressing NHIA", "Clinical Services", 1500),
    # ── PARTIAL EXCLUSION (50:50 shared cost) ─────────────────────────
    ("Meropenem 1g Injection NHIA", "Pharmacy", 18725),
    ("Meropenem 500mg Injection NHIA", "Pharmacy", 10210),
    ("Gelofusine 500ml Infusion NHIA", "Pharmacy", 4500),
    ("Lipid Emulsion 10% 20% Infusion NHIA", "Pharmacy", 15600),
    ("Total Parenteral Nutrition TPN NHIA", "Clinical Services", 30900),
    ("Lithium Carbonate Capsules 300mg", "Pharmacy", 417),
    ("Pimozide Tablets 4mg", "Pharmacy", 438),
    ("Budesonide Formoterol Inhaler 160/4.5ug", "Pharmacy", 10000),
    ("Rosiglitazone Tablet 4mg", "Pharmacy", 308),
    ("Vildagliptin Tablet 50mg", "Pharmacy", 279),
    ("Vildagliptin Metformin Tablet 50/500mg", "Pharmacy", 289),
    ("Saxagliptin Metformin Tablet 5/500mg", "Pharmacy", 500),
    ("Saxagliptin 5mg Tablet", "Pharmacy", 320),
    ("Sitagliptin Tablet 50mg", "Pharmacy", 108),
    ("Sitagliptin Tablet 100mg", "Pharmacy", 145),
    ("Sitagliptin Metformin Tablet 50/1000mg", "Pharmacy", 200),
]

created = 0
updated = 0
svc_created = 0

for name, category, price in services:
    svc, was_new_svc = Service.objects.update_or_create(
        name=name,
        defaults={"category": category, "price": price, "is_active": True}
    )
    if was_new_svc:
        svc_created += 1

    _, was_created = ServiceTariff.objects.update_or_create(
        service=svc,
        patient_type='retainership',
        hmo=hmo,
        defaults={"price": price, "is_active": True}
    )
    if was_created:
        created += 1
    else:
        updated += 1

print(f"\nNew services added:    {svc_created}")
print(f"NHIA Tariffs created:  {created}")
print(f"NHIA Tariffs updated:  {updated}")
print(f"Total tariffs set:     {created + updated}")
print(f"\nDone! All NHIA tariffs from the 47-page price list are now live.")
