# Generated by Django 5.2.9 on 2026-04-24 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_hmo_patient_patient_type_patient_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_code',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
