# Generated by Django 5.0.3 on 2025-11-19 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_name', models.CharField(default='Dannys Wellness Clinic', max_length=200)),
                ('clinic_address', models.TextField(blank=True, null=True)),
                ('clinic_city', models.CharField(blank=True, max_length=100, null=True)),
                ('clinic_state', models.CharField(blank=True, max_length=100, null=True)),
                ('clinic_zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('clinic_country', models.CharField(default='United States', max_length=100)),
                ('clinic_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('clinic_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('clinic_website', models.URLField(blank=True, null=True)),
                ('monday_open', models.TimeField(blank=True, null=True)),
                ('monday_close', models.TimeField(blank=True, null=True)),
                ('tuesday_open', models.TimeField(blank=True, null=True)),
                ('tuesday_close', models.TimeField(blank=True, null=True)),
                ('wednesday_open', models.TimeField(blank=True, null=True)),
                ('wednesday_close', models.TimeField(blank=True, null=True)),
                ('thursday_open', models.TimeField(blank=True, null=True)),
                ('thursday_close', models.TimeField(blank=True, null=True)),
                ('friday_open', models.TimeField(blank=True, null=True)),
                ('friday_close', models.TimeField(blank=True, null=True)),
                ('saturday_open', models.TimeField(blank=True, null=True)),
                ('saturday_close', models.TimeField(blank=True, null=True)),
                ('sunday_open', models.TimeField(blank=True, null=True)),
                ('sunday_close', models.TimeField(blank=True, null=True)),
                ('appointment_duration_minutes', models.IntegerField(default=30)),
                ('max_appointments_per_day', models.IntegerField(default=50)),
                ('allow_online_booking', models.BooleanField(default=True)),
                ('require_email_verification', models.BooleanField(default=False)),
                ('email_notifications_enabled', models.BooleanField(default=True)),
                ('sms_notifications_enabled', models.BooleanField(default=False)),
                ('appointment_reminder_hours', models.IntegerField(default=24)),
                ('session_timeout_minutes', models.IntegerField(default=30)),
                ('password_reset_enabled', models.BooleanField(default=True)),
                ('two_factor_auth_enabled', models.BooleanField(default=False)),
                ('auto_backup_enabled', models.BooleanField(default=True)),
                ('backup_frequency_days', models.IntegerField(default=7)),
                ('last_backup_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
                'db_table': 'system_settings',
            },
        ),
    ]
